table DimCustomer
	lineageTag: c000dcd7-f108-411e-8eb4-bdfb38e84df2

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 31339db9-12d8-4649-8b66-01ce158a170f
		isDefaultLabel
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = User

	column CustomerName
		dataType: string
		lineageTag: d1b3dbc5-d78f-4529-808e-68c071b5383f
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 391c5dbd-8df3-40b9-9cbf-516d349d76eb
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column AccountManager
		dataType: string
		lineageTag: f1e1c4b9-250a-440e-a7d2-ea6ec489922c
		summarizeBy: none
		sourceColumn: AccountManager

		annotation SummarizationSetBy = Automatic

	column PaymentTerms
		dataType: string
		lineageTag: 04714f26-18e1-44b0-b09e-fc7a77646284
		summarizeBy: none
		sourceColumn: PaymentTerms

		annotation SummarizationSetBy = Automatic

	column ContactName
		dataType: string
		lineageTag: 1c32d69b-b97f-47c5-b857-56e31785fac8
		summarizeBy: none
		sourceColumn: ContactName

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 76b1dd14-f411-464c-90ec-d2fcf817d886
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column CreditLimit
		dataType: int64
		formatString: 0
		lineageTag: cc62b440-acc1-4557-b9e9-3b4a44b79a88
		summarizeBy: sum
		sourceColumn: CreditLimit

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: d61a69a6-d369-4954-90de-2235d6f3b56f
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column Street
		dataType: string
		lineageTag: dd382d8b-4e1b-4f97-b403-b6c4008b76a8
		summarizeBy: none
		sourceColumn: Street

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: c705ecf3-4541-455b-8509-85542d1bf857
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 6c64fb8a-5987-46f3-aa2a-13b7b9961e26
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition DimCustomer = m
		mode: import
		queryGroup: 02_Dimensions
		source =
				let
				    Source = CUST_MASTER,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([CustomerID] <> 9999)),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"CustomerID"}, customer_contacts, {"CustomerID"}, "customer_contacts", JoinKind.LeftOuter),
				    #"Expanded customer_contacts" = Table.ExpandTableColumn(#"Merged Queries", "customer_contacts", {"ContactName", "Email", "IsPrimary"}, {"ContactName", "Email", "IsPrimary"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded customer_contacts", {"CustomerID"}, user_details, {"UserID"}, "user_details", JoinKind.LeftOuter),
				    #"Expanded user_details" = Table.ExpandTableColumn(#"Merged Queries1", "user_details", {"CreditLimit", "Phone"}, {"CreditLimit", "Phone"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Expanded user_details", {"AddressID"}, Address, {"AddressID"}, "Address", JoinKind.LeftOuter),
				    #"Expanded Address" = Table.ExpandTableColumn(#"Merged Queries2", "Address", {"Street", "CityName"}, {"Street", "CityName"}),
				    #"Merged Queries3" = Table.NestedJoin(#"Expanded Address", {"CityName"}, cities, {"CityName"}, "cities", JoinKind.LeftOuter),
				    #"Expanded cities" = Table.ExpandTableColumn(#"Merged Queries3", "cities", {"RegionName"}, {"RegionName"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded cities",{"AddressID", "hash_key", "source_id", "IsPrimary"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"CityName", "City"}, {"RegionName", "Region"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

