table FactSales
	lineageTag: f7e21107-32c0-4c48-aa95-8d19ea403ad6

	column LineID
		dataType: string
		lineageTag: adbe3cd6-4080-46da-96b6-52c781819ff7
		isDefaultLabel
		summarizeBy: none
		sourceColumn: LineID

		annotation SummarizationSetBy = Automatic

	column OrderID
		dataType: string
		lineageTag: df44b0c6-9706-47f9-bbc8-77dced1231e6
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 0d8b7842-090d-427a-ac81-5cf68482e5da
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: 3e0c17ef-083a-4f68-9984-7fe2b7716047
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitCost
		dataType: double
		lineageTag: 525baa23-7bbe-4037-913f-51e39025b90b
		summarizeBy: sum
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DiscountPct
		dataType: double
		lineageTag: c7ee80eb-0936-4806-9678-5100f1995638
		summarizeBy: sum
		sourceColumn: DiscountPct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LineTotal
		dataType: double
		lineageTag: fc6a15de-385d-4a01-98c2-e0ed2a1e0f77
		summarizeBy: sum
		sourceColumn: LineTotal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: ca8ab05b-4a29-408c-bb04-5eba4ca1878a
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 20e013b5-2a1b-4bb1-ba27-8902480c5e2f
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column FlagKey
		dataType: int64
		formatString: 0
		lineageTag: 7040188a-c36c-4812-93b1-cfa53025af0a
		summarizeBy: none
		sourceColumn: FlagKey

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: bf27ea10-060a-4411-9281-56b4930ee79f
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

	column ShipToCityKey
		dataType: int64
		formatString: 0
		lineageTag: 1baf1ff4-9f4a-4f3c-9dd7-13f613b3f036
		summarizeBy: count
		sourceColumn: ShipToCityKey

		annotation SummarizationSetBy = Automatic

	column BillToCityKey
		dataType: int64
		formatString: 0
		lineageTag: 959edda7-1fc0-40ac-94d5-40fe646697d2
		summarizeBy: none
		sourceColumn: BillToCityKey

		annotation SummarizationSetBy = Automatic

	partition FactSales = m
		mode: import
		queryGroup: 03_Facts
		source =
				let
				    Source = order_line_items,
				    #"Merged Queries" = Table.NestedJoin(Source, {"OrderID"}, orders, {"OrderID"}, "orders", JoinKind.LeftOuter),
				    #"Expanded orders" = Table.ExpandTableColumn(#"Merged Queries", "orders", {"CustomerName", "CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderDate", "OrderChannel", "Status", "Priority", "OrderTotal"}, {"CustomerName", "CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderDate", "OrderChannel", "Status", "Priority", "OrderTotal"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded orders", {"CustomerName"}, DimCustomer, {"CustomerName"}, "DimCustomer", JoinKind.LeftOuter),
				    #"Expanded DimCustomer" = Table.ExpandTableColumn(#"Merged Queries1", "DimCustomer", {"CustomerID"}, {"CustomerID"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded DimCustomer",{"LineID", "OrderID", "CustomerID", "ProductName", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "CustomerName", "CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderDate", "OrderChannel", "Status", "Priority", "OrderTotal"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Reordered Columns", {"ProductName"}, DimProduct, {"ProductName"}, "DimProduct", JoinKind.LeftOuter),
				    #"Expanded DimProduct" = Table.ExpandTableColumn(#"Merged Queries2", "DimProduct", {"ProductKey"}, {"ProductKey"}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Expanded DimProduct",{"LineID", "OrderID", "CustomerID", "ProductKey", "ProductName", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "CustomerName", "CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderDate", "OrderChannel", "Status", "Priority", "OrderTotal"}),
				    #"Merged Queries3" = Table.NestedJoin(#"Reordered Columns1", {"OrderChannel", "Status", "Priority"}, DimOrderFlags, {"OrderChannel", "Status", "Priority"}, "DimOrderFlags", JoinKind.LeftOuter),
				    #"Expanded DimOrderFlags" = Table.ExpandTableColumn(#"Merged Queries3", "DimOrderFlags", {"FlagKey"}, {"FlagKey"}),
				    #"Reordered Columns2" = Table.ReorderColumns(#"Expanded DimOrderFlags",{"LineID", "OrderID", "CustomerID", "ProductKey", "FlagKey", "ProductName", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "CustomerName", "CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderDate", "OrderChannel", "Status", "Priority", "OrderTotal"}),
				    #"Merged Queries4" = Table.NestedJoin(#"Reordered Columns2", {"ShipToCity"}, DimGeo, {"City"}, "DimGeo", JoinKind.LeftOuter),
				    #"Expanded DimGeo" = Table.ExpandTableColumn(#"Merged Queries4", "DimGeo", {"GeoKey"}, {"GeoKey"}),
				    #"Reordered Columns3" = Table.ReorderColumns(#"Expanded DimGeo",{"LineID", "OrderID", "CustomerID", "ProductKey", "FlagKey", "GeoKey", "ProductName", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "CustomerName", "CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderDate", "OrderChannel", "Status", "Priority", "OrderTotal"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns3",{{"GeoKey", "ShipToCityKey"}}),
				    #"Merged Queries5" = Table.NestedJoin(#"Renamed Columns", {"BillToCity"}, DimGeo, {"City"}, "DimGeo", JoinKind.LeftOuter),
				    #"Expanded DimGeo1" = Table.ExpandTableColumn(#"Merged Queries5", "DimGeo", {"GeoKey"}, {"GeoKey"}),
				    #"Reordered Columns4" = Table.ReorderColumns(#"Expanded DimGeo1",{"LineID", "OrderID", "CustomerID", "ProductKey", "FlagKey", "ShipToCityKey", "GeoKey", "ProductName", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "CustomerName", "CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderDate", "OrderChannel", "Status", "Priority", "OrderTotal"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns4",{{"GeoKey", "BillToCityKey"}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns1",{"LineID", "OrderID", "CustomerID", "ProductKey", "FlagKey", "ShipToCityKey", "BillToCityKey", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "OrderDate"}),
				    #"Reordered Columns5" = Table.ReorderColumns(#"Removed Other Columns",{"LineID", "OrderID", "CustomerID", "ProductKey", "ShipToCityKey", "BillToCityKey", "FlagKey", "OrderDate", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal"})
				in
				    #"Reordered Columns5"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

