table FactOrderFulfillment
	lineageTag: 6fd62f11-5652-43cc-a699-71e269019ce0

	column OrderID
		dataType: string
		lineageTag: c7341dfb-513c-42c9-abba-04dbe1e7121a
		isDefaultLabel
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: aa504916-fb6a-4f20-b444-90948c8fd154
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: d1533bc6-d6b8-49c0-a0ff-ec8e81a9e768
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

	column ShipDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 38c24121-4cd3-41fa-8748-ade484f2344a
		summarizeBy: none
		sourceColumn: ShipDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DeliveryDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8e077138-c437-4055-836b-236d59a64821
		summarizeBy: none
		sourceColumn: DeliveryDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column InvoiceDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 23dac557-7d52-4092-b037-ca13b0d80f4a
		summarizeBy: none
		sourceColumn: InvoiceDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PayDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 1c6d9741-ea7f-4323-aa67-8d6b4ea0062a
		summarizeBy: none
		sourceColumn: PayDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition FactOrderFulfillment = m
		mode: import
		queryGroup: 03_Facts
		source =
				let
				    Source = orders,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"OrderID", "CustomerName", "OrderDate"}),
				    #"Merged Queries Customer" = Table.NestedJoin(#"Removed Other Columns", {"CustomerName"}, Table.Buffer(DimCustomer), {"CustomerName"}, "DimCustomer", JoinKind.LeftOuter),
				    #"Expanded DimCustomer" = Table.ExpandTableColumn(#"Merged Queries Customer", "DimCustomer", {"CustomerID"}, {"CustomerID"}),
				    #"Removed CustomerName" = Table.RemoveColumns(#"Expanded DimCustomer",{"CustomerName"}),
				    
				    // Aggregate Shipments to enforce 1:1 grain per OrderID and buffer in RAM
				    #"Grouped Shipments" = Table.Group(shipments, {"OrderID"}, {{"ShipDate", each List.Max([ShipDate]), type nullable date}, {"DeliveryDate", each List.Max([DeliveryDate]), type nullable date}}),
				    #"Buffered Shipments" = Table.Buffer(#"Grouped Shipments"),
				    #"Merged Shipments" = Table.NestedJoin(#"Removed CustomerName", {"OrderID"}, #"Buffered Shipments", {"OrderID"}, "ShipmentData", JoinKind.LeftOuter),
				    #"Expanded Shipments" = Table.ExpandTableColumn(#"Merged Shipments", "ShipmentData", {"ShipDate", "DeliveryDate"}, {"ShipDate", "DeliveryDate"}),
				    
				    // Join Payments to Invoices, aggregate financial dates by OrderID, and buffer in RAM
				    #"Invoices with Payments" = Table.NestedJoin(INVOICES, {"InvoiceID"}, payments, {"InvoiceID"}, "PaymentDetails", JoinKind.LeftOuter),
				    #"Expanded Payments" = Table.ExpandTableColumn(#"Invoices with Payments", "PaymentDetails", {"PayDate"}, {"PayDate"}),
				    #"Grouped Invoices" = Table.Group(#"Expanded Payments", {"OrderID"}, {{"InvoiceDate", each List.Max([InvoiceDate]), type nullable date}, {"PayDate", each List.Max([PayDate]), type nullable date}}),
				    #"Buffered Invoices" = Table.Buffer(#"Grouped Invoices"),
				    
				    // Join aggregated financial dates back to fulfillment table
				    #"Merged Invoices" = Table.NestedJoin(#"Expanded Shipments", {"OrderID"}, #"Buffered Invoices", {"OrderID"}, "InvoiceData", JoinKind.LeftOuter),
				    #"Expanded InvoiceData" = Table.ExpandTableColumn(#"Merged Invoices", "InvoiceData", {"InvoiceDate", "PayDate"}, {"InvoiceDate", "PayDate"})
				in
				    #"Expanded InvoiceData"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

