table FactInventory
	lineageTag: 8e4bb9f4-398b-4201-9cf3-4aff84f0b699

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: d5727fc0-4e14-4c1c-a6a1-f7145ea80163
		isDefaultLabel
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column YearMonth
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: b33c7bec-4b1b-4e80-9cff-9dd061a3b6b4
		summarizeBy: none
		sourceColumn: YearMonth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Units
		dataType: int64
		formatString: 0
		lineageTag: bcba601d-6e3c-4eef-9154-c1b90b79bedf
		summarizeBy: sum
		sourceColumn: Units

		annotation SummarizationSetBy = Automatic

	partition FactInventory = m
		mode: import
		queryGroup: 03_Facts
		source =
				let
				    Source = inventory,
				    // Promote headers first, then IMMEDIATELY unpivot all non-identity columns.
				    // This removes the hardcoded year-month column list so new years (2026+)
				    // are automatically picked up without any M code changes.
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Promoted Headers", {"ProductName"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "YearMonth"}, {"Value", "Units"}}),
				    // Cast types AFTER unpivot — YearMonth and Units are now single columns, no hardcoding needed
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"ProductName", type text}, {"YearMonth", type date}, {"Units", Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"ProductName"}, Table.Buffer(DimProduct), {"ProductName"}, "products", JoinKind.LeftOuter),
				    #"Expanded products" = Table.ExpandTableColumn(#"Merged Queries", "products", {"ProductKey"}, {"ProductKey"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded products",{"ProductKey", "ProductName", "YearMonth", "Units"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"ProductName"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

