table KeyMeasures
	lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567890

	measure 'Total Sales' = SUM(FactSales[LineTotal])
		formatString: $#,##0.00
		displayFolder: 01_Sales Performance
		lineageTag: b1c2d3e4-f5a6-7890-bcde-f01234567891

	measure 'Total Quantity Sold' = SUM(FactSales[Quantity])
		formatString: #,##0
		displayFolder: 01_Sales Performance
		lineageTag: c1d2e3f4-a5b6-7890-cdef-012345678902

	measure 'Sales Target' = SUM(FactSalesTargets[TargetRevenue])
		formatString: $#,##0.00
		displayFolder: 01_Sales Performance
		lineageTag: d1e2f3a4-b5c6-7890-def0-123456789013

	measure 'Sales Variance' = [Total Sales] - [Sales Target]
		formatString: $#,##0.00;($#,##0.00);"-"
		displayFolder: 01_Sales Performance
		lineageTag: e1f2a3b4-c5d6-7890-ef01-234567890124

	measure 'Sales Variance %' = DIVIDE([Sales Variance], [Sales Target], BLANK())
		formatString: 0.0%;(0.0%);"-"
		displayFolder: 01_Sales Performance
		lineageTag: f1a2b3c4-d5e6-7890-f012-345678901235

	measure 'Sales YTD' = CALCULATE([Total Sales], DATESYTD(DimDate[Date]))
		formatString: $#,##0.00
		displayFolder: 01_Sales Performance
		lineageTag: a2b3c4d5-e6f7-8901-abcd-ef2345678906

	measure 'Sales PYTD' = CALCULATE([Total Sales], DATESYTD(SAMEPERIODLASTYEAR(DimDate[Date])))
		formatString: $#,##0.00
		displayFolder: 01_Sales Performance
		lineageTag: b2c3d4e5-f6a7-8901-bcde-f12345678907

	measure 'Sales YoY Growth %' = DIVIDE([Sales YTD] - [Sales PYTD], [Sales PYTD], BLANK())
		formatString: 0.0%;(0.0%);"-"
		displayFolder: 01_Sales Performance
		lineageTag: c2d3e4f5-a6b7-8901-cdef-023456789018

	measure 'Sales MoM Growth %' =
			VAR _CurrentMonth = [Total Sales]
			VAR _PreviousMonth = CALCULATE([Total Sales], DATEADD(DimDate[Date], -1, MONTH))
			RETURN DIVIDE(_CurrentMonth - _PreviousMonth, _PreviousMonth, BLANK())
		formatString: 0.0%;(0.0%);"-"
		displayFolder: 01_Sales Performance
		lineageTag: d2e3f4a5-b6c7-8901-def0-134567890129

	measure 'Avg Order Value' = DIVIDE([Total Sales], DISTINCTCOUNT(FactSales[OrderID]), BLANK())
		formatString: $#,##0.00
		displayFolder: 01_Sales Performance
		lineageTag: e2f3a4b5-c6d7-8901-ef01-24567890013a

	measure 'Total COGS' = SUMX(FactSales, FactSales[Quantity] * FactSales[UnitCost])
		formatString: $#,##0.00
		displayFolder: 02_Profitability
		lineageTag: f2a3b4c5-d6e7-8901-f012-3456789001ab

	measure 'Gross Profit' = [Total Sales] - [Total COGS]
		formatString: $#,##0.00
		displayFolder: 02_Profitability
		lineageTag: a3b4c5d6-e7f8-9012-abcd-ef34567890bc

	measure 'Gross Margin %' = DIVIDE([Gross Profit], [Total Sales], BLANK())
		formatString: 0.0%;(0.0%);"-"
		displayFolder: 02_Profitability
		lineageTag: b3c4d5e6-f7a8-9012-bcde-f034567890cd

	measure 'Total Stock Units' = SUM(FactInventory[Units])
		formatString: #,##0
		displayFolder: 03_Supply & Inventory
		lineageTag: c3d4e5f6-a7b8-9012-cdef-1034567890de

	measure 'Avg Daily Sales (30d)' =
			CALCULATE(
			    DIVIDE([Total Quantity Sold], 30),
			    DATESINPERIOD(DimDate[Date], LASTDATE(DimDate[Date]), -30, DAY)
			)
		formatString: #,##0.0
		displayFolder: 03_Supply & Inventory
		lineageTag: d3e4f5a6-b7c8-9012-def0-2034567890ef

	measure 'Days of Inventory Cover' = DIVIDE([Total Stock Units], [Avg Daily Sales (30d)], BLANK())
		formatString: #,##0.0 "days"
		displayFolder: 03_Supply & Inventory
		lineageTag: e3f4a5b6-c7d8-9012-ef01-3034567890f0

	measure 'Total Orders' = DISTINCTCOUNT(FactOrderFulfillment[OrderID])
		formatString: #,##0
		displayFolder: 04_Fulfillment & Logistics
		lineageTag: f3a4b5c6-d7e8-9012-f012-4034567890a1

	measure 'On-Time Deliveries' =
			CALCULATE(
			    [Total Orders],
			    FILTER(
			        FactOrderFulfillment,
			        FactOrderFulfillment[DeliveryDate] <= FactOrderFulfillment[ShipDate] + 7
			    )
			)
		formatString: #,##0
		displayFolder: 04_Fulfillment & Logistics
		lineageTag: a4b5c6d7-e8f9-0123-abcd-ef456789012b

	measure 'OTIF %' = DIVIDE([On-Time Deliveries], [Total Orders], BLANK())
		formatString: 0.0%;(0.0%);"-"
		displayFolder: 04_Fulfillment & Logistics
		lineageTag: b4c5d6e7-f8a9-0123-bcde-f0456789023c

	measure 'Avg Lead Time (Days)' =
			AVERAGEX(
			    FactOrderFulfillment,
			    DATEDIFF(
			        FactOrderFulfillment[OrderDate],
			        FactOrderFulfillment[DeliveryDate],
			        DAY
			    )
			)
		formatString: #,##0.0 "days"
		displayFolder: 04_Fulfillment & Logistics
		lineageTag: c4d5e6f7-a8b9-0123-cdef-10456789034d

	measure 'Avg Ship-to-Delivery (Days)' =
			AVERAGEX(
			    FactOrderFulfillment,
			    DATEDIFF(
			        FactOrderFulfillment[ShipDate],
			        FactOrderFulfillment[DeliveryDate],
			        DAY
			    )
			)
		formatString: #,##0.0 "days"
		displayFolder: 04_Fulfillment & Logistics
		lineageTag: d4e5f6a7-b8c9-0123-def0-20456789045e

	measure 'Total Campaign Spend' = SUM(FactCampaignSpend[Spend])
		formatString: $#,##0.00
		displayFolder: 05_Marketing & Campaigns
		lineageTag: e4f5a6b7-c8d9-0123-ef01-30456789056f

	measure 'Marketing ROI' = DIVIDE([Total Sales], [Total Campaign Spend], BLANK())
		formatString: #,##0.00"x"
		displayFolder: 05_Marketing & Campaigns
		lineageTag: f4a5b6c7-d8e9-0123-f012-40456789067a

	measure 'Revenue per Campaign \$' = DIVIDE([Total Sales], DISTINCTCOUNT(FactCampaignSpend[CampaignKey]), BLANK())
		formatString: $#,##0.00
		displayFolder: 05_Marketing & Campaigns
		lineageTag: a5b6c7d8-e9f0-1234-abcd-ef567890178b

	measure 'Total Customers' = DISTINCTCOUNT(FactSales[CustomerID])
		formatString: #,##0
		displayFolder: 06_Customer Analytics
		lineageTag: b5c6d7e8-f0a1-1234-bcde-f0567890289c

	measure 'Sales per Customer' = DIVIDE([Total Sales], [Total Customers], BLANK())
		formatString: $#,##0.00
		displayFolder: 06_Customer Analytics
		lineageTag: c5d6e7f8-a0b1-1234-cdef-106789039ad

	measure 'Repeat Customer Rate %' =
			VAR _RepeatCustomers =
			    COUNTROWS(
			        FILTER(
			            ADDCOLUMNS(
			                VALUES(FactSales[CustomerID]),
			                "OrderCount", CALCULATE(DISTINCTCOUNT(FactSales[OrderID]))
			            ),
			            [OrderCount] > 1
			        )
			    )
			RETURN
			    DIVIDE(_RepeatCustomers, [Total Customers], BLANK())
		formatString: 0.0%;(0.0%);"-"
		displayFolder: 06_Customer Analytics
		lineageTag: d5e6f7a8-b0c1-1234-def0-2067890ab0be

	measure 'Selected Period Sales' = CALCULATE([Total Sales], ALLSELECTED(DimDate))
		formatString: $#,##0.00
		displayFolder: 07_Dynamic & Context
		lineageTag: e5f6a7b8-c0d1-1234-ef01-3067890bc0cf

	measure 'Running Total Sales' =
			CALCULATE(
			    [Total Sales],
			    FILTER(
			        ALL(DimDate[Date]),
			        DimDate[Date] <= MAX(DimDate[Date])
			    )
			)
		formatString: $#,##0.00
		displayFolder: 07_Dynamic & Context
		lineageTag: f5a6b7c8-d0e1-1234-f012-4067890cd0d0

	measure 'Sales Rolling 3M' =
			CALCULATE(
			    [Total Sales],
			    DATESINPERIOD(DimDate[Date], LASTDATE(DimDate[Date]), -3, MONTH)
			)
		formatString: $#,##0.00
		displayFolder: 07_Dynamic & Context
		lineageTag: a6b7c8d9-e0f1-2345-abcd-ef678901e0e1

	measure System_Metadata_HTML =
			
			VAR LastRefreshDate = FORMAT(LASTDATE('DimDate'[Date]), "MMMM DD, YYYY hh:mm AM/PM")
			VAR ActiveCampaigns = CALCULATE(COUNTROWS('DimCampaign'))
			VAR TotalStock = FORMAT([Total Stock Units], "#,##0")
			
			RETURN
			"<div style='font-family: Segoe UI, sans-serif; padding: 15px; background-color: #F9FAFB; border-radius: 8px; border: 1px solid #E5E7EB; box-shadow: 2px 2px 4px rgba(0,0,0,0.05);'>
			    <h3 style='color: #1E3A8A; margin-top: 0; font-size: 16px; font-weight: 600;'>System & Data Status</h3>
			    <hr style='border: none; border-top: 1px solid #E5E7EB; margin-bottom: 10px;' />
			    <table style='width: 100%; font-size: 13px; color: #64748B; border-collapse: collapse;'>
			        <tr>
			            <td style='padding: 4px 0;'><strong>Last Data Refresh:</strong></td>
			            <td style='text-align: right;'>" & LastRefreshDate & "</td>
			        </tr>
			        <tr>
			            <td style='padding: 4px 0;'><strong>Active Marketing Campaigns:</strong></td>
			            <td style='text-align: right;'>" & ActiveCampaigns & "</td>
			        </tr>
			        <tr>
			            <td style='padding: 4px 0;'><strong>Monitored Stock Units:</strong></td>
			            <td style='text-align: right;'>" & TotalStock & "</td>
			        </tr>
			    </table>
			</div>"
		displayFolder: 00_HTML & UI/UX
		lineageTag: 46b23cd1-2143-4f3b-b047-089e6c96406a

	measure UI_4K_LandingPage_Refined = ```
			
			VAR CurrentUserEmail = USERPRINCIPALNAME()
			VAR DotPosition = SEARCH(".", CurrentUserEmail, 1, 0)
			VAR UserFirstName = IF(DotPosition > 0 && DotPosition < SEARCH("@", CurrentUserEmail, 1, 0), UPPER(LEFT(CurrentUserEmail, 1)) & MID(CurrentUserEmail, 2, DotPosition - 2), "Sohila")
			
			VAR RefreshDate = FORMAT(MAX('DimDate'[Date]), "MMMM DD, YYYY")
			
			RETURN
			"<!DOCTYPE html>
			<html style='height: 100%; width: 100%; margin: 0; padding: 0;'>
			<head>
			<meta charset='UTF-8'>
			<style>
			    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap');
			    
			    @keyframes fadeInUp {
			        from { opacity: 0; transform: translateY(50px); }
			        to { opacity: 1; transform: translateY(0); }
			    }
			    
			    @keyframes floatOrb {
			        0% { transform: translateY(0px) scale(1); }
			        50% { transform: translateY(-40px) scale(1.08); }
			        100% { transform: translateY(0px) scale(1); }
			    }
			    
			    @keyframes pulseGlow {
			        0% { box-shadow: 0 0 0 0 rgba(59, 130, 246, 0.6); }
			        70% { box-shadow: 0 0 0 25px rgba(59, 130, 246, 0); }
			        100% { box-shadow: 0 0 0 0 rgba(59, 130, 246, 0); }
			    }
			
			    body {
			        margin: 0;
			        padding: 0;
			        width: 100%;
			        height: 100%;
			        background-color: #0B0F19;
			        background-image: 
			            radial-gradient(circle at 10% 20%, rgba(30, 58, 138, 0.2) 0%, transparent 50%),
			            radial-gradient(circle at 90% 80%, rgba(124, 58, 237, 0.15) 0%, transparent 50%);
			        display: flex;
			        flex-direction: column;
			        align-items: center;
			        justify-content: center;
			        font-family: 'Outfit', 'Segoe UI', sans-serif;
			        overflow: hidden;
			        box-sizing: border-box;
			        position: relative;
			    }
			
			    /* Floating Neon Backdrop Orbs */
			    .orb {
			        position: absolute;
			        border-radius: 50%;
			        filter: blur(140px);
			        z-index: 1;
			        pointer-events: none;
			    }
			
			    .orb-1 {
			        width: 800px;
			        height: 800px;
			        background: rgba(59, 130, 246, 0.18);
			        top: -200px;
			        left: 10%;
			        animation: floatOrb 18s infinite ease-in-out;
			    }
			
			    .orb-2 {
			        width: 900px;
			        height: 900px;
			        background: rgba(124, 58, 237, 0.14);
			        bottom: -250px;
			        right: 10%;
			        animation: floatOrb 22s infinite ease-in-out -6s;
			    }
			
			    .orb-3 {
			        width: 600px;
			        height: 600px;
			        background: rgba(16, 185, 129, 0.08);
			        top: 30%;
			        left: 45%;
			        animation: floatOrb 25s infinite ease-in-out -12s;
			    }
			
			    .wrapper {
			        display: flex;
			        flex-direction: column;
			        justify-content: space-between;
			        width: 92%;
			        max-width: 1800px;
			        height: 90vh;
			        z-index: 2;
			        box-sizing: border-box;
			        animation: fadeInUp 1s cubic-bezier(0.16, 1, 0.3, 1) forwards;
			    }
			
			    /* Top Header Bar */
			    .header-bar {
			        display: flex;
			        justify-content: space-between;
			        align-items: center;
			        border-bottom: 1px solid rgba(255, 255, 255, 0.05);
			        padding-bottom: 30px;
			    }
			
			    .brand {
			        display: flex;
			        align-items: center;
			        gap: 15px;
			    }
			
			    .brand-icon {
			        font-size: 32px;
			    }
			
			    .brand-text {
			        font-size: 26px;
			        font-weight: 700;
			        letter-spacing: 1px;
			        color: #FFFFFF;
			    }
			
			    .metadata-badges {
			        display: flex;
			        gap: 15px;
			    }
			
			    .badge {
			        background: rgba(255, 255, 255, 0.03);
			        border: 1px solid rgba(255, 255, 255, 0.08);
			        border-radius: 50px;
			        padding: 10px 24px;
			        font-size: 15px;
			        color: #94A3B8;
			        display: flex;
			        align-items: center;
			        gap: 8px;
			    }
			
			    .badge strong {
			        color: #FFFFFF;
			        font-weight: 600;
			    }
			
			    .dot {
			        width: 8px;
			        height: 8px;
			        border-radius: 50%;
			        background: #10B981;
			        box-shadow: 0 0 10px #10B981;
			    }
			
			    /* Hero Welcome Panel */
			    .hero-panel {
			        margin-top: 4vh;
			        text-align: center;
			    }
			
			    .hero-pre {
			        font-size: 16px;
			        font-weight: 700;
			        color: #38BDF8;
			        letter-spacing: 3px;
			        text-transform: uppercase;
			        margin-bottom: 12px;
			    }
			
			    .hero-title {
			        font-size: 64px;
			        font-weight: 800;
			        color: #FFFFFF;
			        margin: 0;
			        letter-spacing: -2px;
			        line-height: 1.15;
			    }
			
			    .hero-title strong {
			        background: linear-gradient(135deg, #60A5FA 0%, #7C3AED 100%);
			        -webkit-background-clip: text;
			        -webkit-text-fill-color: transparent;
			    }
			
			    .hero-desc {
			        font-size: 20px;
			        color: #94A3B8;
			        line-height: 1.6;
			        margin: 15px auto 0 auto;
			        max-width: 800px;
			    }
			
			    /* Launchpad Cards Grid */
			    .card-grid {
			        display: grid;
			        grid-template-columns: repeat(4, 1fr);
			        gap: 30px;
			        margin: 5vh 0;
			    }
			
			    .card {
			        background: rgba(30, 41, 59, 0.4);
			        border-radius: 28px;
			        border: 1px solid rgba(255, 255, 255, 0.05);
			        padding: 35px;
			        display: flex;
			        flex-direction: column;
			        justify-content: space-between;
			        height: 310px;
			        box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
			        transition: all 0.4s cubic-bezier(0.16, 1, 0.3, 1);
			        box-sizing: border-box;
			        cursor: pointer;
			    }
			
			    .card:hover {
			        transform: translateY(-12px);
			        background: rgba(30, 41, 59, 0.65);
			    }
			
			    /* Neon Glow borders on hover based on type */
			    .card:nth-child(1):hover { border-color: #3B82F6; box-shadow: 0 20px 40px rgba(59, 130, 246, 0.15); }
			    .card:nth-child(2):hover { border-color: #10B981; box-shadow: 0 20px 40px rgba(16, 185, 129, 0.15); }
			    .card:nth-child(3):hover { border-color: #8B5CF6; box-shadow: 0 20px 40px rgba(139, 92, 246, 0.15); }
			    .card:nth-child(4):hover { border-color: #F59E0B; box-shadow: 0 20px 40px rgba(245, 158, 17, 0.15); }
			
			    .card-top {
			        display: flex;
			        justify-content: space-between;
			        align-items: center;
			    }
			
			    .card-icon {
			        width: 64px;
			        height: 64px;
			        border-radius: 16px;
			        display: flex;
			        align-items: center;
			        justify-content: center;
			        font-size: 30px;
			    }
			
			    .card:nth-child(1) .card-icon { background: rgba(59, 130, 246, 0.15); color: #60A5FA; }
			    .card:nth-child(2) .card-icon { background: rgba(16, 185, 129, 0.15); color: #34D399; }
			    .card:nth-child(3) .card-icon { background: rgba(124, 58, 237, 0.15); color: #A78BFA; }
			    .card:nth-child(4) .card-icon { background: rgba(245, 158, 11, 0.15); color: #FBBF24; }
			
			    .card-arrow {
			        font-size: 24px;
			        color: #475569;
			        transition: all 0.3s ease;
			    }
			
			    .card:hover .card-arrow {
			        transform: translateX(8px);
			    }
			    .card:nth-child(1):hover .card-arrow { color: #60A5FA; }
			    .card:nth-child(2):hover .card-arrow { color: #34D399; }
			    .card:nth-child(3):hover .card-arrow { color: #A78BFA; }
			    .card:nth-child(4):hover .card-arrow { color: #FBBF24; }
			
			    .card-info {
			        margin-top: 25px;
			    }
			
			    .card-title {
			        font-size: 26px;
			        font-weight: 600;
			        color: #FFFFFF;
			        margin: 0 0 10px 0;
			    }
			
			    .card-desc {
			        font-size: 15px;
			        color: #94A3B8;
			        line-height: 1.6;
			        margin: 0;
			    }
			
			    /* Navigation & CTA launch area */
			    .launch-area {
			        display: flex;
			        flex-direction: column;
			        align-items: center;
			        margin-top: 2vh;
			    }
			
			    .launch-btn {
			        background: linear-gradient(135deg, #3B82F6 0%, #7C3AED 100%);
			        color: #FFFFFF;
			        font-size: 20px;
			        font-weight: 700;
			        padding: 24px 70px;
			        border-radius: 50px;
			        cursor: pointer;
			        border: none;
			        animation: pulseGlow 3s infinite;
			        transition: all 0.3s cubic-bezier(0.16, 1, 0.3, 1);
			        letter-spacing: 1px;
			        box-shadow: 0 8px 30px rgba(59, 130, 246, 0.4);
			        text-transform: uppercase;
			    }
			
			    .launch-btn:hover {
			        transform: scale(1.05);
			        box-shadow: 0 15px 40px rgba(124, 58, 237, 0.6);
			    }
			</style>
			</head>
			<body>
			    <!-- Ambient Glowing Orbs -->
			    <div class='orb orb-1'></div>
			    <div class='orb orb-2'></div>
			    <div class='orb orb-3'></div>
			
			    <div class='wrapper'>
			        <!-- Top Header Bar -->
			        <div class='header-bar'>
			            <div class='brand'>
			                <span class='brand-icon'>📊</span>
			                <span class='brand-text'>S&OP INTELLIGENCE</span>
			            </div>
			            <div class='metadata-badges'>
			                <div class='badge'>
			                    <span class='dot'></span>
			                    Environment: <strong>Production</strong>
			                </div>
			                <div class='badge'>
			                    Sync: <strong>" & RefreshDate & "</strong>
			                </div>
			                <div class='badge'>
			                    Engine: <strong>DeepClean OS</strong>
			                </div>
			            </div>
			        </div>
			
			        <!-- Hero Welcome Panel -->
			        <div class='hero-panel'>
			            <div class='hero-pre'>Control Center Active</div>
			            <h1 class='hero-title'>Welcome back, <strong>" & UserFirstName & "</strong></h1>
			            <p class='hero-desc'>Enterprise demand planning, customer channels, logistics status, and marketing ROI cubes have successfully updated. Select an operations portal below to begin analysis.</p>
			        </div>
			
			        <!-- Launchpad Directory Cards -->
			        <div class='card-grid'>
			            <div class='card'>
			                <div class='card-top'>
			                    <div class='card-icon'>📈</div>
			                    <div class='card-arrow'>→</div>
			                </div>
			                <div class='card-info'>
			                    <h3 class='card-title'>Executive Summary</h3>
			                    <p class='card-desc'>High-level operations overview. Track aggregate sales revenues, gross margins, and dynamic variance targets.</p>
			                </div>
			            </div>
			            <div class='card'>
			                <div class='card-top'>
			                    <div class='card-icon'>👥</div>
			                    <div class='card-arrow'>→</div>
			                    </div>
			                <div class='card-info'>
			                    <h3 class='card-title'>Demand & Customers</h3>
			                    <p class='card-desc'>Detailed customer analytics. Deep dive into purchase channels, customer segmentations, and regional geographic maps.</p>
			                </div>
			            </div>
			            <div class='card'>
			                <div class='card-top'>
			                    <div class='card-icon'>📦</div>
			                    <div class='card-arrow'>→</div>
			                </div>
			                <div class='card-info'>
			                    <h3 class='card-title'>Inventory & Logistics</h3>
			                    <p class='card-desc'>Operations and supply chain control. Monitor warehouse capacities, days of cover, and shipping status.</p>
			                </div>
			            </div>
			            <div class='card'>
			                <div class='card-top'>
			                    <div class='card-icon'>📢</div>
			                    <div class='card-arrow'>→</div>
			                </div>
			                <div class='card-info'>
			                    <h3 class='card-title'>Marketing & ROI</h3>
			                    <p class='card-desc'>Marketing spend analysis. Evaluate click-through rates, active campaigns budget allocation, and conversion indexes.</p>
			                </div>
			            </div>
			        </div>
			
			        <!-- Center CTA area -->
			        <div class='launch-area'>
			            <button class='launch-btn'>Launch Workspace</button>
			        </div>
			    </div>
			</body>
			</html>"
	```
		displayFolder: 00_HTML & UI/UX
		lineageTag: c24854a0-be84-4227-82e7-62895f2f823e

	column Value
		isHidden
		lineageTag: cabf892f-0e48-4e97-86a5-bbc4fc7ec7d1
		isNameInferred
		sourceColumn: [Value]

	partition KeyMeasures = calculated
		mode: import
		source = {(BLANK())}

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

