table KeyMeasures
	lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567890

	measure 'Total Sales' = SUM(FactSales[LineTotal])
		formatString: $#,##0.00
		displayFolder: 01_Sales Performance
		lineageTag: b1c2d3e4-f5a6-7890-bcde-f01234567891

	measure 'Total Quantity Sold' = SUM(FactSales[Quantity])
		formatString: #,##0
		displayFolder: 01_Sales Performance
		lineageTag: c1d2e3f4-a5b6-7890-cdef-012345678902

	measure 'Sales Target' = SUM(FactSalesTargets[TargetRevenue])
		formatString: $#,##0.00
		displayFolder: 01_Sales Performance
		lineageTag: d1e2f3a4-b5c6-7890-def0-123456789013

	measure 'Sales Variance' = [Total Sales] - [Sales Target]
		formatString: $#,##0.00;($#,##0.00);"-"
		displayFolder: 01_Sales Performance
		lineageTag: e1f2a3b4-c5d6-7890-ef01-234567890124

	measure 'Sales Variance %' = DIVIDE([Sales Variance], [Sales Target], BLANK())
		formatString: 0.0%;(0.0%);"-"
		displayFolder: 01_Sales Performance
		lineageTag: f1a2b3c4-d5e6-7890-f012-345678901235

	measure 'Sales YTD' = CALCULATE([Total Sales], DATESYTD(DimDate[Date]))
		formatString: $#,##0.00
		displayFolder: 01_Sales Performance
		lineageTag: a2b3c4d5-e6f7-8901-abcd-ef2345678906

	measure 'Sales PYTD' = CALCULATE([Total Sales], DATESYTD(SAMEPERIODLASTYEAR(DimDate[Date])))
		formatString: $#,##0.00
		displayFolder: 01_Sales Performance
		lineageTag: b2c3d4e5-f6a7-8901-bcde-f12345678907

	measure 'Sales YoY Growth %' = DIVIDE([Sales YTD] - [Sales PYTD], [Sales PYTD], BLANK())
		formatString: 0.0%;(0.0%);"-"
		displayFolder: 01_Sales Performance
		lineageTag: c2d3e4f5-a6b7-8901-cdef-023456789018

	measure 'Sales MoM Growth %' =
			VAR _CurrentMonth = [Total Sales]
			VAR _PreviousMonth = CALCULATE([Total Sales], DATEADD(DimDate[Date], -1, MONTH))
			RETURN DIVIDE(_CurrentMonth - _PreviousMonth, _PreviousMonth, BLANK())
		formatString: 0.0%;(0.0%);"-"
		displayFolder: 01_Sales Performance
		lineageTag: d2e3f4a5-b6c7-8901-def0-134567890129

	measure 'Avg Order Value' = DIVIDE([Total Sales], DISTINCTCOUNT(FactSales[OrderID]), BLANK())
		formatString: $#,##0.00
		displayFolder: 01_Sales Performance
		lineageTag: e2f3a4b5-c6d7-8901-ef01-24567890013a

	measure 'Total COGS' = SUMX(FactSales, FactSales[Quantity] * FactSales[UnitCost])
		formatString: $#,##0.00
		displayFolder: 02_Profitability
		lineageTag: f2a3b4c5-d6e7-8901-f012-3456789001ab

	measure 'Gross Profit' = [Total Sales] - [Total COGS]
		formatString: $#,##0.00
		displayFolder: 02_Profitability
		lineageTag: a3b4c5d6-e7f8-9012-abcd-ef34567890bc

	measure 'Gross Margin %' = DIVIDE([Gross Profit], [Total Sales], BLANK())
		formatString: 0.0%;(0.0%);"-"
		displayFolder: 02_Profitability
		lineageTag: b3c4d5e6-f7a8-9012-bcde-f034567890cd

	measure 'Total Stock Units' = SUM(FactInventory[Units])
		formatString: #,##0
		displayFolder: 03_Supply & Inventory
		lineageTag: c3d4e5f6-a7b8-9012-cdef-1034567890de

	measure 'Avg Daily Sales (30d)' =
			CALCULATE(
			    DIVIDE([Total Quantity Sold], 30),
			    DATESINPERIOD(DimDate[Date], LASTDATE(DimDate[Date]), -30, DAY)
			)
		formatString: #,##0.0
		displayFolder: 03_Supply & Inventory
		lineageTag: d3e4f5a6-b7c8-9012-def0-2034567890ef

	measure 'Days of Inventory Cover' = DIVIDE([Total Stock Units], [Avg Daily Sales (30d)], BLANK())
		formatString: #,##0.0 "days"
		displayFolder: 03_Supply & Inventory
		lineageTag: e3f4a5b6-c7d8-9012-ef01-3034567890f0

	measure 'Total Orders' = DISTINCTCOUNT(FactOrderFulfillment[OrderID])
		formatString: #,##0
		displayFolder: 04_Fulfillment & Logistics
		lineageTag: f3a4b5c6-d7e8-9012-f012-4034567890a1

	measure 'On-Time Deliveries' =
			CALCULATE(
			    [Total Orders],
			    FILTER(
			        FactOrderFulfillment,
			        FactOrderFulfillment[DeliveryDate] <= FactOrderFulfillment[ShipDate] + 7
			    )
			)
		formatString: #,##0
		displayFolder: 04_Fulfillment & Logistics
		lineageTag: a4b5c6d7-e8f9-0123-abcd-ef456789012b

	measure 'OTIF %' = DIVIDE([On-Time Deliveries], [Total Orders], BLANK())
		formatString: 0.0%;(0.0%);"-"
		displayFolder: 04_Fulfillment & Logistics
		lineageTag: b4c5d6e7-f8a9-0123-bcde-f0456789023c

	measure 'Avg Lead Time (Days)' =
			AVERAGEX(
			    FactOrderFulfillment,
			    DATEDIFF(
			        FactOrderFulfillment[OrderDate],
			        FactOrderFulfillment[DeliveryDate],
			        DAY
			    )
			)
		formatString: #,##0.0 "days"
		displayFolder: 04_Fulfillment & Logistics
		lineageTag: c4d5e6f7-a8b9-0123-cdef-10456789034d

	measure 'Avg Ship-to-Delivery (Days)' =
			AVERAGEX(
			    FactOrderFulfillment,
			    DATEDIFF(
			        FactOrderFulfillment[ShipDate],
			        FactOrderFulfillment[DeliveryDate],
			        DAY
			    )
			)
		formatString: #,##0.0 "days"
		displayFolder: 04_Fulfillment & Logistics
		lineageTag: d4e5f6a7-b8c9-0123-def0-20456789045e

	measure 'Total Campaign Spend' = SUM(FactCampaignSpend[Spend])
		formatString: $#,##0.00
		displayFolder: 05_Marketing & Campaigns
		lineageTag: e4f5a6b7-c8d9-0123-ef01-30456789056f

	measure 'Marketing ROI' = DIVIDE([Total Sales], [Total Campaign Spend], BLANK())
		formatString: #,##0.00"x"
		displayFolder: 05_Marketing & Campaigns
		lineageTag: f4a5b6c7-d8e9-0123-f012-40456789067a

	measure 'Revenue per Campaign \$' = DIVIDE([Total Sales], DISTINCTCOUNT(FactCampaignSpend[CampaignKey]), BLANK())
		formatString: $#,##0.00
		displayFolder: 05_Marketing & Campaigns
		lineageTag: a5b6c7d8-e9f0-1234-abcd-ef567890178b

	measure 'Total Customers' = DISTINCTCOUNT(FactSales[CustomerID])
		formatString: #,##0
		displayFolder: 06_Customer Analytics
		lineageTag: b5c6d7e8-f0a1-1234-bcde-f0567890289c

	measure 'Sales per Customer' = DIVIDE([Total Sales], [Total Customers], BLANK())
		formatString: $#,##0.00
		displayFolder: 06_Customer Analytics
		lineageTag: c5d6e7f8-a0b1-1234-cdef-106789039ad

	measure 'Repeat Customer Rate %' =
			VAR _RepeatCustomers =
			    COUNTROWS(
			        FILTER(
			            ADDCOLUMNS(
			                VALUES(FactSales[CustomerID]),
			                "OrderCount", CALCULATE(DISTINCTCOUNT(FactSales[OrderID]))
			            ),
			            [OrderCount] > 1
			        )
			    )
			RETURN
			    DIVIDE(_RepeatCustomers, [Total Customers], BLANK())
		formatString: 0.0%;(0.0%);"-"
		displayFolder: 06_Customer Analytics
		lineageTag: d5e6f7a8-b0c1-1234-def0-2067890ab0be

	measure 'Selected Period Sales' = CALCULATE([Total Sales], ALLSELECTED(DimDate))
		formatString: $#,##0.00
		displayFolder: 07_Dynamic & Context
		lineageTag: e5f6a7b8-c0d1-1234-ef01-3067890bc0cf

	measure 'Running Total Sales' =
			CALCULATE(
			    [Total Sales],
			    FILTER(
			        ALL(DimDate[Date]),
			        DimDate[Date] <= MAX(DimDate[Date])
			    )
			)
		formatString: $#,##0.00
		displayFolder: 07_Dynamic & Context
		lineageTag: f5a6b7c8-d0e1-1234-f012-4067890cd0d0

	measure 'Sales Rolling 3M' =
			CALCULATE(
			    [Total Sales],
			    DATESINPERIOD(DimDate[Date], LASTDATE(DimDate[Date]), -3, MONTH)
			)
		formatString: $#,##0.00
		displayFolder: 07_Dynamic & Context
		lineageTag: a6b7c8d9-e0f1-2345-abcd-ef678901e0e1

	measure System_Metadata_HTML =
			
			VAR LastRefreshDate = FORMAT(LASTDATE('DimDate'[Date]), "MMMM DD, YYYY hh:mm AM/PM")
			VAR ActiveCampaigns = CALCULATE(COUNTROWS('DimCampaign'))
			VAR TotalStock = FORMAT([Total Stock Units], "#,##0")
			
			RETURN
			"<div style='font-family: Segoe UI, sans-serif; padding: 15px; background-color: #F9FAFB; border-radius: 8px; border: 1px solid #E5E7EB; box-shadow: 2px 2px 4px rgba(0,0,0,0.05);'>
			    <h3 style='color: #1E3A8A; margin-top: 0; font-size: 16px; font-weight: 600;'>System & Data Status</h3>
			    <hr style='border: none; border-top: 1px solid #E5E7EB; margin-bottom: 10px;' />
			    <table style='width: 100%; font-size: 13px; color: #64748B; border-collapse: collapse;'>
			        <tr>
			            <td style='padding: 4px 0;'><strong>Last Data Refresh:</strong></td>
			            <td style='text-align: right;'>" & LastRefreshDate & "</td>
			        </tr>
			        <tr>
			            <td style='padding: 4px 0;'><strong>Active Marketing Campaigns:</strong></td>
			            <td style='text-align: right;'>" & ActiveCampaigns & "</td>
			        </tr>
			        <tr>
			            <td style='padding: 4px 0;'><strong>Monitored Stock Units:</strong></td>
			            <td style='text-align: right;'>" & TotalStock & "</td>
			        </tr>
			    </table>
			</div>"
		displayFolder: 00_HTML & UI/UX
		lineageTag: 46b23cd1-2143-4f3b-b047-089e6c96406a

	measure UI_4K_LandingPage_Refined = ```
			
			VAR CurrentUserEmail = USERPRINCIPALNAME()
			VAR DotPosition = SEARCH(".", CurrentUserEmail, 1, 0)
			VAR UserFirstName = IF(DotPosition > 0 && DotPosition < SEARCH("@", CurrentUserEmail, 1, 0), UPPER(LEFT(CurrentUserEmail, 1)) & MID(CurrentUserEmail, 2, DotPosition - 2), "Sohila")
			
			VAR MetricRevenue = FORMAT([Total Sales], "$#,##0")
			VAR MetricOrders = FORMAT(COUNTROWS('FactSales'), "#,##0")
			VAR MetricCampaigns = FORMAT(COUNTROWS('DimCampaign'), "#,##0")
			VAR MetricStock = FORMAT(SUM('FactInventory'[Units]), "#,##0")
			VAR RefreshDate = FORMAT(MAX('DimDate'[Date]), "MMMM DD, YYYY")
			
			RETURN
			"<!DOCTYPE html>
			<html style='height: 100%; width: 100%; margin: 0; padding: 0;'>
			<head>
			<meta charset='UTF-8'>
			<style>
			    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap');
			    
			    @keyframes fadeInUp {
			        from { opacity: 0; transform: translateY(20px); }
			        to { opacity: 1; transform: translateY(0); }
			    }
			    
			    @keyframes float {
			        0% { transform: translateY(0px); }
			        50% { transform: translateY(-10px); }
			        100% { transform: translateY(0px); }
			    }
			    
			    @keyframes pulseGlow {
			        0% { box-shadow: 0 0 0 0 rgba(59, 130, 246, 0.4); }
			        70% { box-shadow: 0 0 0 15px rgba(59, 130, 246, 0); }
			        100% { box-shadow: 0 0 0 0 rgba(59, 130, 246, 0); }
			    }
			
			    body {
			        margin: 0;
			        padding: 0;
			        width: 100%;
			        height: 100%;
			        background-color: #F9FAFB;
			        background-image: 
			            radial-gradient(circle at 10% 20%, rgba(59, 130, 246, 0.05) 0%, transparent 40%),
			            radial-gradient(circle at 90% 80%, rgba(124, 58, 237, 0.04) 0%, transparent 40%);
			        display: flex;
			        align-items: center;
			        justify-content: center;
			        font-family: 'Outfit', 'Segoe UI', sans-serif;
			        overflow: hidden;
			        box-sizing: border-box;
			    }
			
			    .container {
			        display: flex;
			        width: 90%;
			        max-width: 1600px;
			        height: 85vh;
			        background: rgba(255, 255, 255, 0.7);
			        backdrop-filter: blur(20px);
			        border-radius: 24px;
			        border: 1px solid rgba(229, 231, 235, 0.8);
			        box-shadow: 0 20px 40px rgba(0, 0, 0, 0.03);
			        overflow: hidden;
			        animation: fadeInUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards;
			    }
			
			    /* Sidebar info panel */
			    .side-panel {
			        width: 32%;
			        background: linear-gradient(180deg, #1E3A8A 0%, #111827 100%);
			        padding: 60px 40px;
			        display: flex;
			        flex-direction: column;
			        justify-content: space-between;
			        color: #FFFFFF;
			    }
			
			    .logo-area {
			        display: flex;
			        align-items: center;
			        gap: 12px;
			    }
			
			    .logo-icon {
			        width: 40px;
			        height: 40px;
			        background: rgba(255, 255, 255, 0.1);
			        border-radius: 10px;
			        display: flex;
			        align-items: center;
			        justify-content: center;
			        font-size: 20px;
			    }
			
			    .logo-text {
			        font-size: 20px;
			        font-weight: 700;
			        letter-spacing: -0.5px;
			    }
			
			    .welcome-text {
			        margin-top: 40px;
			    }
			
			    .welcome-text h2 {
			        font-size: 32px;
			        font-weight: 300;
			        margin: 0;
			        line-height: 1.2;
			    }
			
			    .welcome-text h2 strong {
			        font-weight: 700;
			        color: #60A5FA;
			    }
			
			    .welcome-desc {
			        font-size: 15px;
			        color: #9CA3AF;
			        line-height: 1.6;
			        margin-top: 15px;
			    }
			
			    .system-status {
			        margin-top: auto;
			        background: rgba(255, 255, 255, 0.04);
			        border: 1px solid rgba(255, 255, 255, 0.08);
			        border-radius: 16px;
			        padding: 20px;
			    }
			
			    .status-row {
			        display: flex;
			        justify-content: space-between;
			        font-size: 13px;
			        margin-bottom: 8px;
			        color: #9CA3AF;
			    }
			
			    .status-row:last-child { margin-bottom: 0; }
			    .status-row strong { color: #FFFFFF; }
			
			    /* Main area with grid */
			    .main-panel {
			        flex: 1;
			        padding: 60px;
			        display: flex;
			        flex-direction: column;
			        justify-content: space-between;
			        overflow-y: auto;
			    }
			
			    .header-area {
			        display: flex;
			        justify-content: space-between;
			        align-items: flex-start;
			    }
			
			    .header-area h1 {
			        font-size: 36px;
			        font-weight: 700;
			        color: #111827;
			        margin: 0;
			        letter-spacing: -1px;
			    }
			
			    .header-area p {
			        font-size: 14px;
			        color: #6B7280;
			        margin: 5px 0 0 0;
			    }
			
			    /* Cards Grid */
			    .card-grid {
			        display: grid;
			        grid-template-columns: repeat(2, 1fr);
			        gap: 24px;
			        margin: 40px 0;
			    }
			
			    .card {
			        background: #FFFFFF;
			        border-radius: 20px;
			        border: 1px solid #E5E7EB;
			        padding: 30px;
			        display: flex;
			        flex-direction: column;
			        justify-content: space-between;
			        height: 180px;
			        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.01);
			        transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
			        position: relative;
			    }
			
			    .card:hover {
			        transform: translateY(-5px);
			        box-shadow: 0 12px 30px rgba(0, 0, 0, 0.06);
			        border-color: #3B82F6;
			    }
			
			    .card-icon {
			        width: 48px;
			        height: 48px;
			        border-radius: 12px;
			        display: flex;
			        align-items: center;
			        justify-content: center;
			        font-size: 22px;
			        margin-bottom: 15px;
			    }
			
			    .card:nth-child(1) .card-icon { background: rgba(59, 130, 246, 0.08); color: #3B82F6; }
			    .card:nth-child(2) .card-icon { background: rgba(16, 185, 129, 0.08); color: #10B981; }
			    .card:nth-child(3) .card-icon { background: rgba(124, 58, 237, 0.08); color: #7C3AED; }
			    .card:nth-child(4) .card-icon { background: rgba(245, 158, 11, 0.08); color: #F59E0B; }
			
			    .card-num {
			        font-size: 32px;
			        font-weight: 700;
			        color: #111827;
			        margin: 0;
			    }
			
			    .card-label {
			        font-size: 13px;
			        font-weight: 600;
			        color: #6B7280;
			        text-transform: uppercase;
			        letter-spacing: 1px;
			        margin-top: 5px;
			    }
			
			    /* Navigation & CTA */
			    .cta-area {
			        display: flex;
			        align-items: center;
			        justify-content: space-between;
			        background: #F3F4F6;
			        border-radius: 16px;
			        padding: 20px 30px;
			    }
			
			    .cta-text {
			        font-size: 15px;
			        font-weight: 500;
			        color: #374151;
			    }
			
			    .cta-btn {
			        background: #3B82F6;
			        color: #FFFFFF;
			        font-size: 14px;
			        font-weight: 600;
			        padding: 12px 28px;
			        border-radius: 30px;
			        cursor: pointer;
			        border: none;
			        animation: pulseGlow 2.5s infinite;
			        transition: all 0.3s ease;
			    }
			
			    .cta-btn:hover {
			        background: #2563EB;
			    }
			</style>
			</head>
			<body>
			    <div class='container'>
			        <!-- Sidebar Panel -->
			        <div class='side-panel'>
			            <div class='logo-area'>
			                <div class='logo-icon'>📊</div>
			                <span class='logo-text'>S&OP INTELLIGENCE</span>
			            </div>
			            
			            <div class='welcome-text'>
			                <h2>Hello, <strong>" & UserFirstName & "</strong></h2>
			                <p class='welcome-desc'>Welcome back to the S&OP Control Center. All local pipelines are active and fully synchronized. Enterprise demand forecasts, campaign spends, and logistics matrices are calculated and ready for visual analysis.</p>
			            </div>
			            
			            <div class='system-status'>
			                <div class='status-row'>
			                    <span>Data Source</span>
			                    <strong>Local SQL Server</strong>
			                </div>
			                <div class='status-row'>
			                    <span>Last Sync</span>
			                    <strong>" & RefreshDate & "</strong>
			                </div>
			                <div class='status-row'>
			                    <span>Pipeline Engine</span>
			                    <strong>DeepClean OS</strong>
			                </div>
			            </div>
			        </div>
			
			        <!-- Main Content Panel -->
			        <div class='main-panel'>
			            <div class='header-area'>
			                <div>
			                    <h1>Executive Overview</h1>
			                    <p>High-level key performance metrics across sales, inventory, and marketing divisions.</p>
			                </div>
			            </div>
			
			            <div class='card-grid'>
			                <div class='card'>
			                    <div class='card-icon'>💰</div>
			                    <div>
			                        <div class='card-num'>" & MetricRevenue & "</div>
			                        <div class='card-label'>Total Sales Revenue</div>
			                    </div>
			                </div>
			                <div class='card'>
			                    <div class='card-icon'>📦</div>
			                    <div>
			                        <div class='card-num'>" & MetricOrders & "</div>
			                        <div class='card-label'>Orders Processed</div>
			                    </div>
			                </div>
			                <div class='card'>
			                    <div class='card-icon'>📢</div>
			                    <div>
			                        <div class='card-num'>" & MetricCampaigns & "</div>
			                        <div class='card-label'>Marketing Campaigns</div>
			                    </div>
			                </div>
			                <div class='card'>
			                    <div class='card-icon'>📥</div>
			                    <div>
			                        <div class='card-num'>" & MetricStock & "</div>
			                        <div class='card-label'>Stock Units (Qty)</div>
			                    </div>
			                </div>
			            </div>
			
			            <div class='cta-area'>
			                <span class='cta-text'>Ready to begin your data analysis session?</span>
			                <button class='cta-btn'>Enter Dashboard</button>
			            </div>
			        </div>
			    </div>
			</body>
			</html>"
			```
			```
		displayFolder: 00_HTML & UI/UX
		lineageTag: c24854a0-be84-4227-82e7-62895f2f823e

	column Value
		isHidden
		lineageTag: cabf892f-0e48-4e97-86a5-bbc4fc7ec7d1
		isNameInferred
		sourceColumn: [Value]

	partition KeyMeasures = calculated
		mode: import
		source = {(BLANK())}

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

