table KeyMeasures
	lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567890

	measure 'Total Sales' = SUM(FactSales[LineTotal])
		formatString: $#,##0.00
		displayFolder: 01_Sales Performance
		lineageTag: b1c2d3e4-f5a6-7890-bcde-f01234567891

	measure 'Total Quantity Sold' = SUM(FactSales[Quantity])
		formatString: #,##0
		displayFolder: 01_Sales Performance
		lineageTag: c1d2e3f4-a5b6-7890-cdef-012345678902

	measure 'Sales Target' = SUM(FactSalesTargets[TargetRevenue])
		formatString: $#,##0.00
		displayFolder: 01_Sales Performance
		lineageTag: d1e2f3a4-b5c6-7890-def0-123456789013

	measure 'Sales Variance' = [Total Sales] - [Sales Target]
		formatString: $#,##0.00;($#,##0.00);"-"
		displayFolder: 01_Sales Performance
		lineageTag: e1f2a3b4-c5d6-7890-ef01-234567890124

	measure 'Sales Variance %' = DIVIDE([Sales Variance], [Sales Target], BLANK())
		formatString: 0.0%;(0.0%);"-"
		displayFolder: 01_Sales Performance
		lineageTag: f1a2b3c4-d5e6-7890-f012-345678901235

	measure 'Sales YTD' = CALCULATE([Total Sales], DATESYTD(DimDate[Date]))
		formatString: $#,##0.00
		displayFolder: 01_Sales Performance
		lineageTag: a2b3c4d5-e6f7-8901-abcd-ef2345678906

	measure 'Sales PYTD' = CALCULATE([Total Sales], DATESYTD(SAMEPERIODLASTYEAR(DimDate[Date])))
		formatString: $#,##0.00
		displayFolder: 01_Sales Performance
		lineageTag: b2c3d4e5-f6a7-8901-bcde-f12345678907

	measure 'Sales YoY Growth %' = DIVIDE([Sales YTD] - [Sales PYTD], [Sales PYTD], BLANK())
		formatString: 0.0%;(0.0%);"-"
		displayFolder: 01_Sales Performance
		lineageTag: c2d3e4f5-a6b7-8901-cdef-023456789018

	measure 'Sales MoM Growth %' =
			VAR _CurrentMonth = [Total Sales]
			VAR _PreviousMonth = CALCULATE([Total Sales], DATEADD(DimDate[Date], -1, MONTH))
			RETURN DIVIDE(_CurrentMonth - _PreviousMonth, _PreviousMonth, BLANK())
		formatString: 0.0%;(0.0%);"-"
		displayFolder: 01_Sales Performance
		lineageTag: d2e3f4a5-b6c7-8901-def0-134567890129

	measure 'Avg Order Value' = DIVIDE([Total Sales], DISTINCTCOUNT(FactSales[OrderID]), BLANK())
		formatString: $#,##0.00
		displayFolder: 01_Sales Performance
		lineageTag: e2f3a4b5-c6d7-8901-ef01-24567890013a

	measure 'Total COGS' = SUMX(FactSales, FactSales[Quantity] * FactSales[UnitCost])
		formatString: $#,##0.00
		displayFolder: 02_Profitability
		lineageTag: f2a3b4c5-d6e7-8901-f012-3456789001ab

	measure 'Gross Profit' = [Total Sales] - [Total COGS]
		formatString: $#,##0.00
		displayFolder: 02_Profitability
		lineageTag: a3b4c5d6-e7f8-9012-abcd-ef34567890bc

	measure 'Gross Margin %' = DIVIDE([Gross Profit], [Total Sales], BLANK())
		formatString: 0.0%;(0.0%);"-"
		displayFolder: 02_Profitability
		lineageTag: b3c4d5e6-f7a8-9012-bcde-f034567890cd

	measure 'Total Stock Units' = SUM(FactInventory[Units])
		formatString: #,##0
		displayFolder: 03_Supply & Inventory
		lineageTag: c3d4e5f6-a7b8-9012-cdef-1034567890de

	measure 'Avg Daily Sales (30d)' =
			CALCULATE(
			    DIVIDE([Total Quantity Sold], 30),
			    DATESINPERIOD(DimDate[Date], LASTDATE(DimDate[Date]), -30, DAY)
			)
		formatString: #,##0.0
		displayFolder: 03_Supply & Inventory
		lineageTag: d3e4f5a6-b7c8-9012-def0-2034567890ef

	measure 'Days of Inventory Cover' = DIVIDE([Total Stock Units], [Avg Daily Sales (30d)], BLANK())
		formatString: #,##0.0 "days"
		displayFolder: 03_Supply & Inventory
		lineageTag: e3f4a5b6-c7d8-9012-ef01-3034567890f0

	measure 'Total Orders' = DISTINCTCOUNT(FactOrderFulfillment[OrderID])
		formatString: #,##0
		displayFolder: 04_Fulfillment & Logistics
		lineageTag: f3a4b5c6-d7e8-9012-f012-4034567890a1

	measure 'On-Time Deliveries' =
			CALCULATE(
			    [Total Orders],
			    FILTER(
			        FactOrderFulfillment,
			        FactOrderFulfillment[DeliveryDate] <= FactOrderFulfillment[ShipDate] + 7
			    )
			)
		formatString: #,##0
		displayFolder: 04_Fulfillment & Logistics
		lineageTag: a4b5c6d7-e8f9-0123-abcd-ef456789012b

	measure 'OTIF %' = DIVIDE([On-Time Deliveries], [Total Orders], BLANK())
		formatString: 0.0%;(0.0%);"-"
		displayFolder: 04_Fulfillment & Logistics
		lineageTag: b4c5d6e7-f8a9-0123-bcde-f0456789023c

	measure 'Avg Lead Time (Days)' =
			AVERAGEX(
			    FactOrderFulfillment,
			    DATEDIFF(
			        FactOrderFulfillment[OrderDate],
			        FactOrderFulfillment[DeliveryDate],
			        DAY
			    )
			)
		formatString: #,##0.0 "days"
		displayFolder: 04_Fulfillment & Logistics
		lineageTag: c4d5e6f7-a8b9-0123-cdef-10456789034d

	measure 'Avg Ship-to-Delivery (Days)' =
			AVERAGEX(
			    FactOrderFulfillment,
			    DATEDIFF(
			        FactOrderFulfillment[ShipDate],
			        FactOrderFulfillment[DeliveryDate],
			        DAY
			    )
			)
		formatString: #,##0.0 "days"
		displayFolder: 04_Fulfillment & Logistics
		lineageTag: d4e5f6a7-b8c9-0123-def0-20456789045e

	measure 'Total Campaign Spend' = SUM(FactCampaignSpend[Spend])
		formatString: $#,##0.00
		displayFolder: 05_Marketing & Campaigns
		lineageTag: e4f5a6b7-c8d9-0123-ef01-30456789056f

	measure 'Marketing ROI' = DIVIDE([Total Sales], [Total Campaign Spend], BLANK())
		formatString: #,##0.00"x"
		displayFolder: 05_Marketing & Campaigns
		lineageTag: f4a5b6c7-d8e9-0123-f012-40456789067a

	measure 'Revenue per Campaign \$' = DIVIDE([Total Sales], DISTINCTCOUNT(FactCampaignSpend[CampaignKey]), BLANK())
		formatString: $#,##0.00
		displayFolder: 05_Marketing & Campaigns
		lineageTag: a5b6c7d8-e9f0-1234-abcd-ef567890178b

	measure 'Total Customers' = DISTINCTCOUNT(FactSales[CustomerID])
		formatString: #,##0
		displayFolder: 06_Customer Analytics
		lineageTag: b5c6d7e8-f0a1-1234-bcde-f0567890289c

	measure 'Sales per Customer' = DIVIDE([Total Sales], [Total Customers], BLANK())
		formatString: $#,##0.00
		displayFolder: 06_Customer Analytics
		lineageTag: c5d6e7f8-a0b1-1234-cdef-106789039ad

	measure 'Repeat Customer Rate %' =
			VAR _RepeatCustomers =
			    COUNTROWS(
			        FILTER(
			            ADDCOLUMNS(
			                VALUES(FactSales[CustomerID]),
			                "OrderCount", CALCULATE(DISTINCTCOUNT(FactSales[OrderID]))
			            ),
			            [OrderCount] > 1
			        )
			    )
			RETURN
			    DIVIDE(_RepeatCustomers, [Total Customers], BLANK())
		formatString: 0.0%;(0.0%);"-"
		displayFolder: 06_Customer Analytics
		lineageTag: d5e6f7a8-b0c1-1234-def0-2067890ab0be

	measure 'Selected Period Sales' = CALCULATE([Total Sales], ALLSELECTED(DimDate))
		formatString: $#,##0.00
		displayFolder: 07_Dynamic & Context
		lineageTag: e5f6a7b8-c0d1-1234-ef01-3067890bc0cf

	measure 'Running Total Sales' =
			CALCULATE(
			    [Total Sales],
			    FILTER(
			        ALL(DimDate[Date]),
			        DimDate[Date] <= MAX(DimDate[Date])
			    )
			)
		formatString: $#,##0.00
		displayFolder: 07_Dynamic & Context
		lineageTag: f5a6b7c8-d0e1-1234-f012-4067890cd0d0

	measure 'Sales Rolling 3M' =
			CALCULATE(
			    [Total Sales],
			    DATESINPERIOD(DimDate[Date], LASTDATE(DimDate[Date]), -3, MONTH)
			)
		formatString: $#,##0.00
		displayFolder: 07_Dynamic & Context
		lineageTag: a6b7c8d9-e0f1-2345-abcd-ef678901e0e1

	measure System_Metadata_HTML =
			
			VAR LastRefreshDate = FORMAT(LASTDATE('DimDate'[Date]), "MMMM DD, YYYY hh:mm AM/PM")
			VAR ActiveCampaigns = CALCULATE(COUNTROWS('DimCampaign'))
			VAR TotalStock = FORMAT([Total Stock Units], "#,##0")
			
			RETURN
			"<div style='font-family: Segoe UI, sans-serif; padding: 15px; background-color: #F9FAFB; border-radius: 8px; border: 1px solid #E5E7EB; box-shadow: 2px 2px 4px rgba(0,0,0,0.05);'>
			    <h3 style='color: #1E3A8A; margin-top: 0; font-size: 16px; font-weight: 600;'>System & Data Status</h3>
			    <hr style='border: none; border-top: 1px solid #E5E7EB; margin-bottom: 10px;' />
			    <table style='width: 100%; font-size: 13px; color: #64748B; border-collapse: collapse;'>
			        <tr>
			            <td style='padding: 4px 0;'><strong>Last Data Refresh:</strong></td>
			            <td style='text-align: right;'>" & LastRefreshDate & "</td>
			        </tr>
			        <tr>
			            <td style='padding: 4px 0;'><strong>Active Marketing Campaigns:</strong></td>
			            <td style='text-align: right;'>" & ActiveCampaigns & "</td>
			        </tr>
			        <tr>
			            <td style='padding: 4px 0;'><strong>Monitored Stock Units:</strong></td>
			            <td style='text-align: right;'>" & TotalStock & "</td>
			        </tr>
			    </table>
			</div>"
		displayFolder: 00_HTML & UI/UX
		lineageTag: 46b23cd1-2143-4f3b-b047-089e6c96406a

	measure UI_4K_LandingPage_Refined = ```
			
			VAR CurrentUserEmail = USERPRINCIPALNAME()
			VAR DotPosition = SEARCH(".", CurrentUserEmail, 1, 0)
			VAR UserFirstName = IF(DotPosition > 0 && DotPosition < SEARCH("@", CurrentUserEmail, 1, 0), UPPER(LEFT(CurrentUserEmail, 1)) & MID(CurrentUserEmail, 2, DotPosition - 2), "Sohila")
			
			VAR MetricOrders = FORMAT(COUNTROWS('FactSales'), "#,##0")
			VAR MetricCampaigns = FORMAT(COUNTROWS('DimCampaign'), "#,##0")
			VAR MetricStock = FORMAT(SUM('FactInventory'[Units]), "#,##0")
			VAR RefreshDate = FORMAT(MAX('DimDate'[Date]), "MMMM DD, YYYY")
			
			RETURN
			"<!DOCTYPE html>
			<html style='height: 100%; width: 100%; margin: 0; padding: 0;'>
			<head>
			<style>
			    /* Elegant Slide and Fade Animation */
			    @keyframes fadeInUp {
			        from { opacity: 0; transform: translateY(3vh); }
			        to { opacity: 1; transform: translateY(0); }
			    }
			    
			    @keyframes pulseGlow {
			        0% { box-shadow: 0 0 0 0 rgba(59, 130, 246, 0.4); }
			        70% { box-shadow: 0 0 0 2vh rgba(59, 130, 246, 0); }
			        100% { box-shadow: 0 0 0 0 rgba(59, 130, 246, 0); }
			    }
			
			    body {
			        margin: 0;
			        padding: 0;
			        width: 100%;
			        height: 100%;
			        /* Theme Background: F9FAFB */
			        background-color: #F9FAFB;
			        /* Decorative background shapes using Theme Colors */
			        background-image: 
			            radial-gradient(circle at 15% 50%, rgba(59, 130, 246, 0.08) 0%, transparent 50%),
			            radial-gradient(circle at 85% 30%, rgba(124, 58, 237, 0.05) 0%, transparent 50%);
			        display: flex;
			        align-items: center;
			        justify-content: center;
			        font-family: 'Segoe UI', sans-serif;
			        overflow: hidden;
			        box-sizing: border-box;
			    }
			
			    /* Main Content Wrapper */
			    .hero-container {
			        text-align: center;
			        width: 85%;
			        max-width: 90vw;
			        animation: fadeInUp 1s cubic-bezier(0.2, 0.8, 0.2, 1) forwards;
			        z-index: 10;
			        position: relative;
			    }
			
			    /* Typography using Theme Text Classes */
			    h1 { 
			        /* Theme Text: title -> #111827 */
			        color: #111827; 
			        font-size: 4.5vw; 
			        margin: 0 0 1vh 0; 
			        font-weight: 300; 
			        letter-spacing: -0.01em; 
			    }
			    
			    h1 strong { 
			        /* Theme Accent: #1E3A8A */
			        color: #1E3A8A; 
			        font-family: 'Segoe UI Semibold', sans-serif; 
			    }
			    
			    .subtitle { 
			        /* Theme Text: body -> #4B5563 */
			        color: #4B5563; 
			        font-size: 1.2vw; 
			        margin-bottom: 6vh; 
			        font-weight: 400; 
			        max-width: 60%;
			        margin-left: auto;
			        margin-right: auto;
			        line-height: 1.6;
			    }
			
			    /* Asymmetric Data Metric Grid */
			    .data-grid {
			        display: grid;
			        grid-template-columns: repeat(3, 1fr);
			        gap: 2.5vw;
			        margin-bottom: 7vh;
			    }
			
			    /* Elegant Metric Cards matching Theme Visual Styles */
			    .data-card {
			        background-color: #FFFFFF;
			        padding: 5vh 2vw;
			        border-radius: 1.5vw;
			        border: 1px solid #E5E7EB;
			        /* Theme DropShadow */
			        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.03);
			        transition: all 0.4s ease;
			        position: relative;
			        overflow: hidden;
			    }
			
			    /* Distinct top border for each card using Theme Palette */
			    .data-card:nth-child(1) { border-top: 0.4vh solid #3B82F6; } /* Blue */
			    .data-card:nth-child(2) { border-top: 0.4vh solid #7C3AED; } /* Purple */
			    .data-card:nth-child(3) { border-top: 0.4vh solid #10B981; } /* Green */
			
			    .data-card:hover { 
			        transform: translateY(-0.8vh); 
			        box-shadow: 0 12px 25px rgba(0, 0, 0, 0.08); 
			    }
			    
			    .data-value { 
			        /* Theme Text: callout -> #1E3A8A */
			        font-size: 3.8vw; 
			        font-weight: 700; 
			        color: #1E3A8A; 
			        margin-bottom: 1vh; 
			        font-family: 'Segoe UI Semibold', sans-serif;
			    }
			    
			    .data-label { 
			        /* Theme Text: header -> #374151 */
			        font-size: 0.9vw; 
			        color: #374151; 
			        text-transform: uppercase; 
			        letter-spacing: 0.15vw; 
			        font-weight: 600;
			    }
			
			    /* Refined CTA Button */
			    .cta-visual {
			        display: inline-block;
			        /* Theme Primary: #3B82F6 */
			        background-color: #3B82F6;
			        color: #FFFFFF;
			        font-size: 1.1vw;
			        font-family: 'Segoe UI Semibold', sans-serif;
			        padding: 2vh 5vw;
			        border-radius: 5vw;
			        letter-spacing: 0.05vw;
			        animation: pulseGlow 3s infinite;
			        cursor: pointer; /* Suggests interactivity */
			    }
			
			    .footer { 
			        margin-top: 5vh; 
			        font-size: 0.8vw; 
			        color: #64748B; 
			    }
			</style>
			</head>
			<body>
			    <div class='hero-container'>
			        <h1>Omnichannel <strong>S&OP Intelligence</strong></h1>
			        <p class='subtitle'>Welcome back, " & UserFirstName & ". The data pipelines have successfully synchronized. Your enterprise logistics, inventory margins, and active campaign metrics are ready for review.</p>
			        
			        <div class='data-grid'>
			            <div class='data-card'>
			                <div class='data-value'>" & MetricOrders & "</div>
			                <div class='data-label'>Processed Orders</div>
			            </div>
			            <div class='data-card'>
			                <div class='data-value'>" & MetricCampaigns & "</div>
			                <div class='data-label'>Active Campaigns</div>
			            </div>
			            <div class='data-card'>
			                <div class='data-value'>" & MetricStock & "</div>
			                <div class='data-label'>Stock Units (Qty)</div>
			            </div>
			        </div>
			
			        <div class='cta-visual'>Enter Executive Dashboard</div>
			        
			        <div class='footer'>Latest Synchronization: " & RefreshDate & " | Automated via DeepClean OS</div>
			    </div>
			</body>
			</html>"
			```
		displayFolder: 00_HTML & UI/UX
		lineageTag: c24854a0-be84-4227-82e7-62895f2f823e

	column Value
		isHidden
		lineageTag: cabf892f-0e48-4e97-86a5-bbc4fc7ec7d1
		isNameInferred
		sourceColumn: [Value]

	partition KeyMeasures = calculated
		mode: import
		source = {(BLANK())}

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

