createOrReplace

	model Model
		culture: en-US
		defaultPowerBIDataSourceVersion: powerBI_V3
		sourceQueryCulture: en-001
		dataAccessOptions
			legacyRedirects
			returnErrorValuesAsNull

		table DimCustomer
			lineageTag: c000dcd7-f108-411e-8eb4-bdfb38e84df2

			column CustomerID
				dataType: int64
				formatString: 0
				lineageTag: 31339db9-12d8-4649-8b66-01ce158a170f
				isDefaultLabel
				summarizeBy: none
				sourceColumn: CustomerID

				annotation SummarizationSetBy = User

			column CustomerName
				dataType: string
				lineageTag: d1b3dbc5-d78f-4529-808e-68c071b5383f
				summarizeBy: none
				sourceColumn: CustomerName

				annotation SummarizationSetBy = Automatic

			column Segment
				dataType: string
				lineageTag: 391c5dbd-8df3-40b9-9cbf-516d349d76eb
				summarizeBy: none
				sourceColumn: Segment

				annotation SummarizationSetBy = Automatic

			column AccountManager
				dataType: string
				lineageTag: f1e1c4b9-250a-440e-a7d2-ea6ec489922c
				summarizeBy: none
				sourceColumn: AccountManager

				annotation SummarizationSetBy = Automatic

			column PaymentTerms
				dataType: string
				lineageTag: 04714f26-18e1-44b0-b09e-fc7a77646284
				summarizeBy: none
				sourceColumn: PaymentTerms

				annotation SummarizationSetBy = Automatic

			column ContactName
				dataType: string
				lineageTag: 1c32d69b-b97f-47c5-b857-56e31785fac8
				summarizeBy: none
				sourceColumn: ContactName

				annotation SummarizationSetBy = Automatic

			column Email
				dataType: string
				lineageTag: 76b1dd14-f411-464c-90ec-d2fcf817d886
				summarizeBy: none
				sourceColumn: Email

				annotation SummarizationSetBy = Automatic

			column CreditLimit
				dataType: int64
				formatString: 0
				lineageTag: cc62b440-acc1-4557-b9e9-3b4a44b79a88
				summarizeBy: sum
				sourceColumn: CreditLimit

				annotation SummarizationSetBy = Automatic

			column Phone
				dataType: string
				lineageTag: d61a69a6-d369-4954-90de-2235d6f3b56f
				summarizeBy: none
				sourceColumn: Phone

				annotation SummarizationSetBy = Automatic

			column Street
				dataType: string
				lineageTag: dd382d8b-4e1b-4f97-b403-b6c4008b76a8
				summarizeBy: none
				sourceColumn: Street

				annotation SummarizationSetBy = Automatic

			column City
				dataType: string
				lineageTag: c705ecf3-4541-455b-8509-85542d1bf857
				summarizeBy: none
				sourceColumn: City

				annotation SummarizationSetBy = Automatic

			column Region
				dataType: string
				lineageTag: 6c64fb8a-5987-46f3-aa2a-13b7b9961e26
				summarizeBy: none
				sourceColumn: Region

				annotation SummarizationSetBy = Automatic

			partition DimCustomer = m
				mode: import
				queryGroup: 02_Dimensions
				source =
						let
						    Source = CUST_MASTER,
						    #"Filtered Rows" = Table.SelectRows(Source, each ([CustomerID] <> 9999)),
						    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"CustomerID"}, customer_contacts, {"CustomerID"}, "customer_contacts", JoinKind.LeftOuter),
						    #"Expanded customer_contacts" = Table.ExpandTableColumn(#"Merged Queries", "customer_contacts", {"ContactName", "Email", "IsPrimary"}, {"ContactName", "Email", "IsPrimary"}),
						    #"Merged Queries1" = Table.NestedJoin(#"Expanded customer_contacts", {"CustomerID"}, user_details, {"UserID"}, "user_details", JoinKind.LeftOuter),
						    #"Expanded user_details" = Table.ExpandTableColumn(#"Merged Queries1", "user_details", {"CreditLimit", "Phone"}, {"CreditLimit", "Phone"}),
						    #"Merged Queries2" = Table.NestedJoin(#"Expanded user_details", {"AddressID"}, Address, {"AddressID"}, "Address", JoinKind.LeftOuter),
						    #"Expanded Address" = Table.ExpandTableColumn(#"Merged Queries2", "Address", {"Street", "CityName"}, {"Street", "CityName"}),
						    #"Merged Queries3" = Table.NestedJoin(#"Expanded Address", {"CityName"}, cities, {"CityName"}, "cities", JoinKind.LeftOuter),
						    #"Expanded cities" = Table.ExpandTableColumn(#"Merged Queries3", "cities", {"RegionName"}, {"RegionName"}),
						    #"Removed Columns" = Table.RemoveColumns(#"Expanded cities",{"AddressID", "hash_key", "source_id", "IsPrimary"}),
						    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"CityName", "City"}, {"RegionName", "Region"}})
						in
						    #"Renamed Columns"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table DimProduct
			lineageTag: 3abb2fd6-8287-4b1c-afad-1c3d284ca288

			column ProductKey
				dataType: int64
				formatString: 0
				lineageTag: 990fdc1c-a1b6-4b74-8d64-e020eaf18c78
				isDefaultLabel
				summarizeBy: none
				sourceColumn: ProductKey

				annotation SummarizationSetBy = Automatic

			column ProductCode
				dataType: string
				lineageTag: a69109ea-6be9-4ae3-86ff-5e2b4b1a03d2
				summarizeBy: none
				sourceColumn: ProductCode

				annotation SummarizationSetBy = Automatic

			column ProductName
				dataType: string
				lineageTag: 52924d7c-be53-4968-b608-85c6ffccc741
				summarizeBy: none
				sourceColumn: ProductName

				annotation SummarizationSetBy = Automatic

			column Brand
				dataType: string
				lineageTag: e03aea82-c112-4ba2-85cf-ffbb49659556
				summarizeBy: none
				sourceColumn: Brand

				annotation SummarizationSetBy = Automatic

			column Category
				dataType: string
				lineageTag: 38b02732-39fb-4f34-bac3-931aa134b326
				summarizeBy: none
				sourceColumn: Category

				annotation SummarizationSetBy = Automatic

			column Subcategory
				dataType: string
				lineageTag: 233f5405-4ea4-4558-9d42-288382dfbf4c
				summarizeBy: none
				sourceColumn: Subcategory

				annotation SummarizationSetBy = Automatic

			column UnitPrice
				dataType: double
				lineageTag: c634f26b-ca4e-4773-859b-524c029b0d61
				summarizeBy: sum
				sourceColumn: UnitPrice

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column PrimarySupplier
				dataType: string
				lineageTag: f73be0c7-85b1-43fa-8a24-77ec0936bc7c
				summarizeBy: none
				sourceColumn: PrimarySupplier

				annotation SummarizationSetBy = Automatic

			partition DimProduct = m
				mode: import
				queryGroup: 02_Dimensions
				source =
						let
						    Source = products,
						    #"Merged Queries" = Table.NestedJoin(Source, {"SubcategoryName"}, subcategories, {"Subcategory"}, "subcategories", JoinKind.LeftOuter),
						    #"Expanded subcategories" = Table.ExpandTableColumn(#"Merged Queries", "subcategories", {"Category"}, {"Category"}),
						    #"Filtered Rows" = Table.SelectRows(#"Expanded subcategories", each ([ProductCode] <> "ZZZ-000") and ([source_id] <> "SAP-099001" and [source_id] <> "SAP-099002")),
						    #"Reordered Columns" = Table.ReorderColumns(#"Filtered Rows",{"ProductCode", "ProductName", "Brand", "Category", "SubcategoryName", "UnitPrice", "PrimarySupplier"}),
						    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"SubcategoryName", "Subcategory"}}),
						    #"Added Index" = Table.AddIndexColumn(#"Renamed Columns", "Index", 1, 1, Int64.Type),
						    #"Reordered Columns1" = Table.ReorderColumns(#"Added Index",{"Index", "ProductCode", "ProductName", "Brand", "Category", "Subcategory", "UnitPrice", "PrimarySupplier"}),
						    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns1",{{"Index", "ProductKey"}}),
						    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns1",{"ProductKey", "ProductCode", "ProductName", "Brand", "Category", "Subcategory", "UnitPrice", "PrimarySupplier"})
						in
						    #"Removed Other Columns"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table DimOrderFlags
			lineageTag: cebf9be6-b93c-49e1-a211-2aafdd730ef3

			column FlagKey
				dataType: int64
				formatString: 0
				lineageTag: 8ed5c2af-7680-4192-ab11-7c9f4029e023
				isDefaultLabel
				summarizeBy: none
				sourceColumn: FlagKey

				annotation SummarizationSetBy = Automatic

			column Channel
				dataType: string
				lineageTag: e1468eb0-3e59-48be-95e7-93bc298fc7ec
				summarizeBy: none
				sourceColumn: Channel

				annotation SummarizationSetBy = Automatic

			column Status
				dataType: string
				lineageTag: dbd985bf-0850-4b12-8a1d-d786688dd78c
				summarizeBy: none
				sourceColumn: Status

				annotation SummarizationSetBy = Automatic

			column Priority
				dataType: string
				lineageTag: 40d0741c-64c6-4546-8249-217bd524e5a7
				summarizeBy: none
				sourceColumn: Priority

				annotation SummarizationSetBy = Automatic

			column OrderChannel
				dataType: int64
				formatString: 0
				lineageTag: 3fbab5cb-c6a1-4492-b1dc-940b5add8ddd
				summarizeBy: none
				sourceColumn: OrderChannel

				annotation SummarizationSetBy = Automatic

			partition DimOrderFlags = m
				mode: import
				queryGroup: 02_Dimensions
				source =
						let
						    Source = orders,
						    #"Removed Other Columns" = Table.SelectColumns(Source,{"OrderChannel", "Status", "Priority"}),
						    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
						    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
						    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "OrderChannel", "Status", "Priority"}),
						    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "FlagKey"}}),
						    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"OrderChannel"}, channels, {"ChannelCode"}, "channels", JoinKind.LeftOuter),
						    #"Expanded channels" = Table.ExpandTableColumn(#"Merged Queries", "channels", {"ChannelName"}, {"ChannelName"}),
						    #"Reordered Columns1" = Table.ReorderColumns(#"Expanded channels",{"FlagKey", "ChannelName", "Status", "Priority"}),
						    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns1",{{"ChannelName", "Channel"}})
						in
						    #"Renamed Columns1"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table FactSales
			lineageTag: f7e21107-32c0-4c48-aa95-8d19ea403ad6

			column LineID
				dataType: string
				lineageTag: adbe3cd6-4080-46da-96b6-52c781819ff7
				isDefaultLabel
				summarizeBy: none
				sourceColumn: LineID

				annotation SummarizationSetBy = Automatic

			column OrderID
				dataType: string
				lineageTag: df44b0c6-9706-47f9-bbc8-77dced1231e6
				summarizeBy: none
				sourceColumn: OrderID

				annotation SummarizationSetBy = Automatic

			column Quantity
				dataType: int64
				formatString: 0
				lineageTag: 0d8b7842-090d-427a-ac81-5cf68482e5da
				summarizeBy: sum
				sourceColumn: Quantity

				annotation SummarizationSetBy = Automatic

			column UnitPrice
				dataType: double
				lineageTag: 3e0c17ef-083a-4f68-9984-7fe2b7716047
				summarizeBy: sum
				sourceColumn: UnitPrice

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column UnitCost
				dataType: double
				lineageTag: 525baa23-7bbe-4037-913f-51e39025b90b
				summarizeBy: sum
				sourceColumn: UnitCost

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column DiscountPct
				dataType: double
				lineageTag: c7ee80eb-0936-4806-9678-5100f1995638
				summarizeBy: sum
				sourceColumn: DiscountPct

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column LineTotal
				dataType: double
				lineageTag: fc6a15de-385d-4a01-98c2-e0ed2a1e0f77
				summarizeBy: sum
				sourceColumn: LineTotal

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column CustomerID
				dataType: int64
				formatString: 0
				lineageTag: ca8ab05b-4a29-408c-bb04-5eba4ca1878a
				summarizeBy: none
				sourceColumn: CustomerID

				annotation SummarizationSetBy = Automatic

			column ProductKey
				dataType: int64
				formatString: 0
				lineageTag: 20e013b5-2a1b-4bb1-ba27-8902480c5e2f
				summarizeBy: none
				sourceColumn: ProductKey

				annotation SummarizationSetBy = Automatic

			column FlagKey
				dataType: int64
				formatString: 0
				lineageTag: 7040188a-c36c-4812-93b1-cfa53025af0a
				summarizeBy: none
				sourceColumn: FlagKey

				annotation SummarizationSetBy = Automatic

			column OrderDate
				dataType: dateTime
				formatString: Short Date
				lineageTag: bf27ea10-060a-4411-9281-56b4930ee79f
				summarizeBy: none
				sourceColumn: OrderDate

				annotation SummarizationSetBy = Automatic

			column ShipToCityKey
				dataType: int64
				formatString: 0
				lineageTag: 1baf1ff4-9f4a-4f3c-9dd7-13f613b3f036
				summarizeBy: count
				sourceColumn: ShipToCityKey

				annotation SummarizationSetBy = Automatic

			column BillToCityKey
				dataType: int64
				formatString: 0
				lineageTag: 959edda7-1fc0-40ac-94d5-40fe646697d2
				summarizeBy: none
				sourceColumn: BillToCityKey

				annotation SummarizationSetBy = Automatic

			partition FactSales = m
				mode: import
				queryGroup: 03_Facts
				source =
						let
						    Source = order_line_items,
						    #"Merged Queries" = Table.NestedJoin(Source, {"OrderID"}, orders, {"OrderID"}, "orders", JoinKind.LeftOuter),
						    #"Expanded orders" = Table.ExpandTableColumn(#"Merged Queries", "orders", {"CustomerName", "CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderDate", "OrderChannel", "Status", "Priority", "OrderTotal"}, {"CustomerName", "CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderDate", "OrderChannel", "Status", "Priority", "OrderTotal"}),
						    #"Merged Queries1" = Table.NestedJoin(#"Expanded orders", {"CustomerName"}, DimCustomer, {"CustomerName"}, "DimCustomer", JoinKind.LeftOuter),
						    #"Expanded DimCustomer" = Table.ExpandTableColumn(#"Merged Queries1", "DimCustomer", {"CustomerID"}, {"CustomerID"}),
						    #"Reordered Columns" = Table.ReorderColumns(#"Expanded DimCustomer",{"LineID", "OrderID", "CustomerID", "ProductName", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "CustomerName", "CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderDate", "OrderChannel", "Status", "Priority", "OrderTotal"}),
						    #"Merged Queries2" = Table.NestedJoin(#"Reordered Columns", {"ProductName"}, DimProduct, {"ProductName"}, "DimProduct", JoinKind.LeftOuter),
						    #"Expanded DimProduct" = Table.ExpandTableColumn(#"Merged Queries2", "DimProduct", {"ProductKey"}, {"ProductKey"}),
						    #"Reordered Columns1" = Table.ReorderColumns(#"Expanded DimProduct",{"LineID", "OrderID", "CustomerID", "ProductKey", "ProductName", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "CustomerName", "CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderDate", "OrderChannel", "Status", "Priority", "OrderTotal"}),
						    #"Merged Queries3" = Table.NestedJoin(#"Reordered Columns1", {"OrderChannel", "Status", "Priority"}, DimOrderFlags, {"OrderChannel", "Status", "Priority"}, "DimOrderFlags", JoinKind.LeftOuter),
						    #"Expanded DimOrderFlags" = Table.ExpandTableColumn(#"Merged Queries3", "DimOrderFlags", {"FlagKey"}, {"FlagKey"}),
						    #"Reordered Columns2" = Table.ReorderColumns(#"Expanded DimOrderFlags",{"LineID", "OrderID", "CustomerID", "ProductKey", "FlagKey", "ProductName", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "CustomerName", "CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderDate", "OrderChannel", "Status", "Priority", "OrderTotal"}),
						    #"Merged Queries4" = Table.NestedJoin(#"Reordered Columns2", {"ShipToCity"}, DimGeo, {"City"}, "DimGeo", JoinKind.LeftOuter),
						    #"Expanded DimGeo" = Table.ExpandTableColumn(#"Merged Queries4", "DimGeo", {"GeoKey"}, {"GeoKey"}),
						    #"Reordered Columns3" = Table.ReorderColumns(#"Expanded DimGeo",{"LineID", "OrderID", "CustomerID", "ProductKey", "FlagKey", "GeoKey", "ProductName", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "CustomerName", "CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderDate", "OrderChannel", "Status", "Priority", "OrderTotal"}),
						    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns3",{{"GeoKey", "ShipToCityKey"}}),
						    #"Merged Queries5" = Table.NestedJoin(#"Renamed Columns", {"BillToCity"}, DimGeo, {"City"}, "DimGeo", JoinKind.LeftOuter),
						    #"Expanded DimGeo1" = Table.ExpandTableColumn(#"Merged Queries5", "DimGeo", {"GeoKey"}, {"GeoKey"}),
						    #"Reordered Columns4" = Table.ReorderColumns(#"Expanded DimGeo1",{"LineID", "OrderID", "CustomerID", "ProductKey", "FlagKey", "ShipToCityKey", "GeoKey", "ProductName", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "CustomerName", "CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderDate", "OrderChannel", "Status", "Priority", "OrderTotal"}),
						    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns4",{{"GeoKey", "BillToCityKey"}}),
						    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns1",{"LineID", "OrderID", "CustomerID", "ProductKey", "FlagKey", "ShipToCityKey", "BillToCityKey", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "OrderDate"}),
						    #"Reordered Columns5" = Table.ReorderColumns(#"Removed Other Columns",{"LineID", "OrderID", "CustomerID", "ProductKey", "ShipToCityKey", "BillToCityKey", "FlagKey", "OrderDate", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal"})
						in
						    #"Reordered Columns5"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table DimGeo
			lineageTag: 0df4cd71-0785-4cbe-bfb3-ace1c651e0b9

			column GeoKey
				dataType: int64
				formatString: 0
				lineageTag: 720cd411-1379-4fe1-bf1b-c4bb89f778b0
				isDefaultLabel
				summarizeBy: none
				sourceColumn: GeoKey

				annotation SummarizationSetBy = Automatic

			column City
				dataType: string
				lineageTag: 04dadaba-1105-4f06-8da8-f1ecf9d7d6b9
				summarizeBy: none
				sourceColumn: City

				annotation SummarizationSetBy = Automatic

			column Region
				dataType: string
				lineageTag: af0d8aee-dbe8-41de-8559-5cbb2a37f506
				summarizeBy: none
				sourceColumn: Region

				annotation SummarizationSetBy = Automatic

			partition DimGeo = m
				mode: import
				queryGroup: 02_Dimensions
				source =
						let
						    Source = cities,
						    #"Removed Duplicates" = Table.Distinct(Source),
						    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
						    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "CityName", "RegionName"}),
						    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "GeoKey"}, {"CityName", "City"}, {"RegionName", "Region"}})
						in
						    #"Renamed Columns"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table FactInventory
			lineageTag: 8e4bb9f4-398b-4201-9cf3-4aff84f0b699

			column ProductKey
				dataType: int64
				formatString: 0
				lineageTag: d5727fc0-4e14-4c1c-a6a1-f7145ea80163
				isDefaultLabel
				summarizeBy: none
				sourceColumn: ProductKey

				annotation SummarizationSetBy = Automatic

			column YearMonth
				dataType: dateTime
				formatString: mmmm yyyy
				lineageTag: b33c7bec-4b1b-4e80-9cff-9dd061a3b6b4
				summarizeBy: none
				sourceColumn: YearMonth

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

				annotation PBI_FormatHint = {"isDateTimeCustom":true}

			column Units
				dataType: int64
				formatString: 0
				lineageTag: bcba601d-6e3c-4eef-9154-c1b90b79bedf
				summarizeBy: sum
				sourceColumn: Units

				annotation SummarizationSetBy = Automatic

			partition FactInventory = m
				mode: import
				queryGroup: 03_Facts
				source =
						let
						    Source = inventory,
						    // Promote headers first, then IMMEDIATELY unpivot all non-identity columns.
						    // This removes the hardcoded year-month column list so new years (2026+)
						    // are automatically picked up without any M code changes.
						    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
						    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Promoted Headers", {"ProductName"}, "Attribute", "Value"),
						    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "YearMonth"}, {"Value", "Units"}}),
						    // Cast types AFTER unpivot — YearMonth and Units are now single columns, no hardcoding needed
						    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"ProductName", type text}, {"YearMonth", type date}, {"Units", Int64.Type}}),
						    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"ProductName"}, Table.Buffer(DimProduct), {"ProductName"}, "products", JoinKind.LeftOuter),
						    #"Expanded products" = Table.ExpandTableColumn(#"Merged Queries", "products", {"ProductKey"}, {"ProductKey"}),
						    #"Reordered Columns" = Table.ReorderColumns(#"Expanded products",{"ProductKey", "ProductName", "YearMonth", "Units"}),
						    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"ProductName"})
						in
						    #"Removed Columns"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table DimCampaign
			lineageTag: 5770285e-a20b-4e62-a5a0-91bc16bd6513

			column CampaignKey
				dataType: int64
				formatString: 0
				lineageTag: 89e06d27-fa2f-40ba-8cd5-2a0dc146d2c7
				isDefaultLabel
				summarizeBy: none
				sourceColumn: CampaignKey

				annotation SummarizationSetBy = Automatic

			column CampaignName
				dataType: string
				lineageTag: cf41a097-fddf-4f13-aa0f-801f55fd2c6e
				summarizeBy: none
				sourceColumn: CampaignName

				annotation SummarizationSetBy = Automatic

			column Channel
				dataType: string
				lineageTag: 625c95aa-a8d9-4a09-b911-89120667aef4
				summarizeBy: none
				sourceColumn: Channel

				annotation SummarizationSetBy = Automatic

			column StartDate
				dataType: dateTime
				formatString: Short Date
				lineageTag: 89f6a64b-af08-4a8d-b211-5e8ca25a890c
				summarizeBy: none
				sourceColumn: StartDate

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column EndDate
				dataType: dateTime
				formatString: Short Date
				lineageTag: abfc3cab-0de3-487b-b045-0295e2ccc95b
				summarizeBy: none
				sourceColumn: EndDate

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column Budget
				dataType: int64
				formatString: 0
				lineageTag: 246c8e02-a57f-4118-b639-ff665ba1371a
				summarizeBy: sum
				sourceColumn: Budget

				annotation SummarizationSetBy = Automatic

			partition DimCampaign = m
				mode: import
				queryGroup: 02_Dimensions
				source =
						let
						    Source = CAMPAIGN_LOG,
						    #"Removed Other Columns" = Table.SelectColumns(Source,{"CampaignName", "Channel", "StartDate", "EndDate", "Budget"}),
						    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
						    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
						    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "CampaignName", "Channel", "StartDate", "EndDate", "Budget"}),
						    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "CampaignKey"}})
						in
						    #"Renamed Columns"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table FactCampaignSpend
			lineageTag: fde1d650-ad1c-498a-867c-0ed6f3191761

			column CampaignKey
				dataType: int64
				formatString: 0
				lineageTag: 91539263-06e2-4414-ab3b-e9108ee634e4
				isDefaultLabel
				summarizeBy: none
				sourceColumn: CampaignKey

				annotation SummarizationSetBy = Automatic

			column Date
				dataType: dateTime
				formatString: Short Date
				lineageTag: 40d63c39-0a83-4e14-b808-9669b662379b
				summarizeBy: none
				sourceColumn: Date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column Impressions
				dataType: int64
				formatString: 0
				lineageTag: 61732a3d-c036-477a-af22-0783b09acd10
				summarizeBy: sum
				sourceColumn: Impressions

				annotation SummarizationSetBy = Automatic

			column Clicks
				dataType: int64
				formatString: 0
				lineageTag: 8644fffb-b52e-4530-9680-db0ee5c4bfad
				summarizeBy: sum
				sourceColumn: Clicks

				annotation SummarizationSetBy = Automatic

			column Spend
				dataType: double
				lineageTag: bfafa21d-c58a-4d76-b0b9-e57f0c20439d
				summarizeBy: sum
				sourceColumn: Spend

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			partition FactCampaignSpend = m
				mode: import
				queryGroup: 03_Facts
				source =
						let
						    Source = CAMPAIGN_LOG,
						    #"Merged Queries" = Table.NestedJoin(Source, {"CampaignName"}, DimCampaign, {"CampaignName"}, "DimCampaign", JoinKind.LeftOuter),
						    #"Expanded DimCampaign" = Table.ExpandTableColumn(#"Merged Queries", "DimCampaign", {"CampaignKey"}, {"CampaignKey"}),
						    #"Reordered Columns" = Table.ReorderColumns(#"Expanded DimCampaign",{"CampaignKey", "CampaignName", "Channel", "StartDate", "EndDate", "Budget", "Date", "Impressions", "Clicks", "Spend"}),
						    #"Removed Other Columns" = Table.SelectColumns(#"Reordered Columns",{"CampaignKey", "Date", "Impressions", "Clicks", "Spend"})
						in
						    #"Removed Other Columns"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table FactPromotionCoverage
			lineageTag: 5701e3fd-9be2-499a-bf63-8f3a334a587d

			column CampaignKey
				dataType: int64
				formatString: 0
				lineageTag: 92d2c94a-0d02-4604-be8c-80fe3b324d89
				isDefaultLabel
				summarizeBy: none
				sourceColumn: CampaignKey

				annotation SummarizationSetBy = Automatic

			column ProductKey
				dataType: int64
				formatString: 0
				lineageTag: 6f5050c5-d4cc-4308-b79f-bdbfd33687ef
				summarizeBy: none
				sourceColumn: ProductKey

				annotation SummarizationSetBy = Automatic

			partition FactPromotionCoverage = m
				mode: import
				queryGroup: 03_Facts
				source =
						let
						    Source = campaign_skus,
						    #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(Source, {{"PromotedSKUs", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "PromotedSKUs"),
						    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"PromotedSKUs", type text}}),
						    #"Trimmed Text" = Table.TransformColumns(#"Changed Type",{{"PromotedSKUs", Text.Trim, type text}}),
						    #"Merged Queries" = Table.NestedJoin(#"Trimmed Text", {"CampaignName"}, DimCampaign, {"CampaignName"}, "DimCampaign", JoinKind.LeftOuter),
						    #"Expanded DimCampaign" = Table.ExpandTableColumn(#"Merged Queries", "DimCampaign", {"CampaignKey"}, {"CampaignKey"}),
						    #"Reordered Columns" = Table.ReorderColumns(#"Expanded DimCampaign",{"CampaignKey", "CampaignName", "PromotedSKUs"}),
						    #"Merged Queries1" = Table.NestedJoin(#"Reordered Columns", {"PromotedSKUs"}, DimProduct, {"ProductCode"}, "DimProduct", JoinKind.LeftOuter),
						    #"Expanded DimProduct" = Table.ExpandTableColumn(#"Merged Queries1", "DimProduct", {"ProductKey"}, {"ProductKey"}),
						    #"Reordered Columns1" = Table.ReorderColumns(#"Expanded DimProduct",{"CampaignKey", "ProductKey", "CampaignName", "PromotedSKUs"}),
						    #"Removed Other Columns" = Table.SelectColumns(#"Reordered Columns1",{"CampaignKey", "ProductKey"})
						in
						    #"Removed Other Columns"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table FactOrderFulfillment
			lineageTag: 6fd62f11-5652-43cc-a699-71e269019ce0

			column OrderID
				dataType: string
				lineageTag: c7341dfb-513c-42c9-abba-04dbe1e7121a
				isDefaultLabel
				summarizeBy: none
				sourceColumn: OrderID

				annotation SummarizationSetBy = Automatic

			column CustomerID
				dataType: int64
				formatString: 0
				lineageTag: aa504916-fb6a-4f20-b444-90948c8fd154
				summarizeBy: none
				sourceColumn: CustomerID

				annotation SummarizationSetBy = Automatic

			column OrderDate
				dataType: dateTime
				formatString: Short Date
				lineageTag: d1533bc6-d6b8-49c0-a0ff-ec8e81a9e768
				summarizeBy: none
				sourceColumn: OrderDate

				annotation SummarizationSetBy = Automatic

			column ShipDate
				dataType: dateTime
				formatString: Short Date
				lineageTag: 38c24121-4cd3-41fa-8748-ade484f2344a
				summarizeBy: none
				sourceColumn: ShipDate

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column DeliveryDate
				dataType: dateTime
				formatString: Short Date
				lineageTag: 8e077138-c437-4055-836b-236d59a64821
				summarizeBy: none
				sourceColumn: DeliveryDate

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column InvoiceDate
				dataType: dateTime
				formatString: Short Date
				lineageTag: 23dac557-7d52-4092-b037-ca13b0d80f4a
				summarizeBy: none
				sourceColumn: InvoiceDate

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column PayDate
				dataType: dateTime
				formatString: Short Date
				lineageTag: 1c6d9741-ea7f-4323-aa67-8d6b4ea0062a
				summarizeBy: none
				sourceColumn: PayDate

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			partition FactOrderFulfillment = m
				mode: import
				queryGroup: 03_Facts
				source =
						let
						    Source = orders,
						    #"Removed Other Columns" = Table.SelectColumns(Source,{"OrderID", "CustomerName", "OrderDate"}),
						    #"Merged Queries Customer" = Table.NestedJoin(#"Removed Other Columns", {"CustomerName"}, Table.Buffer(DimCustomer), {"CustomerName"}, "DimCustomer", JoinKind.LeftOuter),
						    #"Expanded DimCustomer" = Table.ExpandTableColumn(#"Merged Queries Customer", "DimCustomer", {"CustomerID"}, {"CustomerID"}),
						    #"Removed CustomerName" = Table.RemoveColumns(#"Expanded DimCustomer",{"CustomerName"}),
						
						    // Aggregate Shipments to enforce 1:1 grain per OrderID and buffer in RAM
						    #"Grouped Shipments" = Table.Group(shipments, {"OrderID"}, {{"ShipDate", each List.Max([ShipDate]), type nullable date}, {"DeliveryDate", each List.Max([DeliveryDate]), type nullable date}}),
						    #"Buffered Shipments" = Table.Buffer(#"Grouped Shipments"),
						    #"Merged Shipments" = Table.NestedJoin(#"Removed CustomerName", {"OrderID"}, #"Buffered Shipments", {"OrderID"}, "ShipmentData", JoinKind.LeftOuter),
						    #"Expanded Shipments" = Table.ExpandTableColumn(#"Merged Shipments", "ShipmentData", {"ShipDate", "DeliveryDate"}, {"ShipDate", "DeliveryDate"}),
						
						    // Join Payments to Invoices, aggregate financial dates by OrderID, and buffer in RAM
						    #"Invoices with Payments" = Table.NestedJoin(INVOICES, {"InvoiceID"}, payments, {"InvoiceID"}, "PaymentDetails", JoinKind.LeftOuter),
						    #"Expanded Payments" = Table.ExpandTableColumn(#"Invoices with Payments", "PaymentDetails", {"PayDate"}, {"PayDate"}),
						    #"Grouped Invoices" = Table.Group(#"Expanded Payments", {"OrderID"}, {{"InvoiceDate", each List.Max([InvoiceDate]), type nullable date}, {"PayDate", each List.Max([PayDate]), type nullable date}}),
						    #"Buffered Invoices" = Table.Buffer(#"Grouped Invoices"),
						
						    // Join aggregated financial dates back to fulfillment table
						    #"Merged Invoices" = Table.NestedJoin(#"Expanded Shipments", {"OrderID"}, #"Buffered Invoices", {"OrderID"}, "InvoiceData", JoinKind.LeftOuter),
						    #"Expanded InvoiceData" = Table.ExpandTableColumn(#"Merged Invoices", "InvoiceData", {"InvoiceDate", "PayDate"}, {"InvoiceDate", "PayDate"})
						in
						    #"Expanded InvoiceData"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table FactSalesTargets
			lineageTag: 5a6adfae-72f4-4e6b-a342-82e5cc140d51

			column Period
				dataType: dateTime
				formatString: mmmm yyyy
				lineageTag: 37a87fab-5f11-4445-834e-b06039eb1ece
				summarizeBy: none
				sourceColumn: Period

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

				annotation PBI_FormatHint = {"isDateTimeCustom":true}

			column TargetRevenue
				dataType: int64
				formatString: 0
				lineageTag: b25c2f8f-8a21-4dd0-8f0d-929ece760570
				summarizeBy: sum
				sourceColumn: TargetRevenue

				annotation SummarizationSetBy = Automatic

			partition FactSalesTargets = m
				mode: import
				queryGroup: 03_Facts
				source =
						let
						    Source = sales_targets
						in
						    Source

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table Security
			lineageTag: ea592985-7e9a-4d86-8d68-38cb6c44f59e

			column UserEmail
				dataType: string
				lineageTag: f027afae-7723-4b72-806d-9fbbcf688603
				summarizeBy: none
				sourceColumn: UserEmail

				annotation SummarizationSetBy = Automatic

			column Region
				dataType: string
				lineageTag: 9ce3c2ed-37a9-4928-b7dd-e4e32b47f4b5
				summarizeBy: none
				sourceColumn: Region

				annotation SummarizationSetBy = Automatic

			partition Security = m
				mode: import
				queryGroup: 04_Support
				source =
						let
						  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
						  #"Navigation 1" = Source{[Item = "security", Kind = "Sheet"]}[Data],
						  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Column1", type text}, {"Column2", type text}}, "en-US"),
						    #"Promoted Headers" = Table.PromoteHeaders(#"Changed column type", [PromoteAllScalars=true]),
						    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"UserEmail", type text}, {"Region", type text}})
						in
						  #"Changed Type"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table DimDate
			lineageTag: a583ffdf-b7dc-4460-b875-5a6e89c57a9b
			dataCategory: Time

			column Date
				dataType: dateTime
				isKey
				formatString: Short Date
				lineageTag: 5574b618-efbd-4e20-88b2-d0c6170dd0a3
				summarizeBy: none
				sourceColumn: Date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column DateKey
				dataType: int64
				formatString: 0
				lineageTag: de34897d-2756-4219-88e1-b249ac8f6202
				isDefaultLabel
				summarizeBy: none
				sourceColumn: DateKey

				annotation SummarizationSetBy = User

			column Year
				dataType: int64
				formatString: 0
				lineageTag: cf81084b-cc84-4d76-9853-82865ef74902
				summarizeBy: sum
				sourceColumn: Year

				annotation SummarizationSetBy = Automatic

			column QuarterNo
				dataType: int64
				formatString: 0
				lineageTag: 5573108c-3a8b-439d-b65d-8d6588e28033
				summarizeBy: sum
				sourceColumn: QuarterNo

				annotation SummarizationSetBy = Automatic

			column Quarter
				dataType: string
				lineageTag: a7f105ab-1e66-4352-9137-c88b287d6c77
				summarizeBy: none
				sourceColumn: Quarter

				annotation SummarizationSetBy = Automatic

			column MonthNo
				dataType: int64
				formatString: 0
				lineageTag: efb6e826-09e2-4640-8a8a-4c5c0290450e
				summarizeBy: sum
				sourceColumn: MonthNo

				annotation SummarizationSetBy = Automatic

			column Month
				dataType: string
				lineageTag: fb009304-c168-4d59-8f3a-15b81fc0f906
				summarizeBy: none
				sourceColumn: Month

				annotation SummarizationSetBy = Automatic

			column MonthShort
				dataType: string
				lineageTag: bd4d55f7-efc1-435b-85da-9ec16fa6cff5
				summarizeBy: none
				sourceColumn: MonthShort

				annotation SummarizationSetBy = Automatic

			column Day
				dataType: int64
				formatString: 0
				lineageTag: 6e59da7f-738f-435a-a093-ef5beda60f75
				summarizeBy: sum
				sourceColumn: Day

				annotation SummarizationSetBy = Automatic

			partition DimDate = m
				mode: import
				queryGroup: 02_Dimensions
				source = ```
						let
						    // 1. Extract the earliest and latest dates across multiple staging tables to avoid orphaned records
						    MinOrder = Date.From(List.Min(orders[OrderDate])),
						    MaxOrder = Date.From(List.Max(orders[OrderDate])),
						    MinCampaign = Date.From(List.Min(CAMPAIGN_LOG[StartDate])),
						    MaxCampaign = Date.From(List.Max(CAMPAIGN_LOG[EndDate])),
						    MinTarget = Date.From(List.Min(sales_targets[Period])),
						    MaxTarget = Date.From(List.Max(sales_targets[Period])),
						
						    // 2. Find the absolute boundaries across the entire model
						    OverallMin = List.Min({MinOrder, MinCampaign, MinTarget}),
						    OverallMax = List.Max({MaxOrder, MaxCampaign, MaxTarget}),
						
						    // 3. Anchor to the start of the first year and end of the final year (Standard Date Table Requirement)
						    StartYear = Date.Year(OverallMin),
						    EndYear = Date.Year(OverallMax),
						    StartDate = #date(StartYear, 1, 1),
						    EndDate = #date(EndYear, 12, 31),
						
						    // 4. Generate the continuous sequence of dates
						    DayCount = Duration.Days(EndDate - StartDate) + 1,
						    Source = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
						    
						    // 5. Convert to table and set the core data type
						    TableFromList = Table.FromList(Source, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
						    ChangedTypeDate = Table.TransformColumnTypes(TableFromList,{{"Date", type date}}),
						
						    // 6. Build the DateKey and standard temporal attributes
						    AddDateKey = Table.AddColumn(ChangedTypeDate, "DateKey", each Date.Year([Date]) * 10000 + Date.Month([Date]) * 100 + Date.Day([Date]), Int64.Type),
						    AddYear = Table.AddColumn(AddDateKey, "Year", each Date.Year([Date]), Int64.Type),
						    AddQuarterNo = Table.AddColumn(AddYear, "QuarterNo", each Date.QuarterOfYear([Date]), Int64.Type),
						    AddQuarter = Table.AddColumn(AddQuarterNo, "Quarter", each "Q" & Text.From([QuarterNo]), type text),
						    AddMonthNo = Table.AddColumn(AddQuarter, "MonthNo", each Date.Month([Date]), Int64.Type),
						    AddMonthName = Table.AddColumn(AddMonthNo, "Month", each Date.MonthName([Date]), type text),
						    AddMonthShort = Table.AddColumn(AddMonthName, "MonthShort", each Text.Start([Month], 3), type text),
						    AddDayOfMonth = Table.AddColumn(AddMonthShort, "Day", each Date.Day([Date]), Int64.Type)
						in
						    AddDayOfMonth
						```

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table KeyMeasures
			lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567890

			measure 'Total Sales' = SUM(FactSales[LineTotal])
				formatString: $#,##0.00
				displayFolder: 01_Sales Performance
				lineageTag: b1c2d3e4-f5a6-7890-bcde-f01234567891

			measure 'Total Quantity Sold' = SUM(FactSales[Quantity])
				formatString: #,##0
				displayFolder: 01_Sales Performance
				lineageTag: c1d2e3f4-a5b6-7890-cdef-012345678902

			measure 'Sales Target' = SUM(FactSalesTargets[TargetRevenue])
				formatString: $#,##0.00
				displayFolder: 01_Sales Performance
				lineageTag: d1e2f3a4-b5c6-7890-def0-123456789013

			measure 'Sales Variance' = [Total Sales] - [Sales Target]
				formatString: $#,##0.00;($#,##0.00);"-"
				displayFolder: 01_Sales Performance
				lineageTag: e1f2a3b4-c5d6-7890-ef01-234567890124

			measure 'Sales Variance %' = DIVIDE([Sales Variance], [Sales Target], BLANK())
				formatString: 0.0%;(0.0%);"-"
				displayFolder: 01_Sales Performance
				lineageTag: f1a2b3c4-d5e6-7890-f012-345678901235

			measure 'Sales YTD' = CALCULATE([Total Sales], DATESYTD(DimDate[Date]))
				formatString: $#,##0.00
				displayFolder: 01_Sales Performance
				lineageTag: a2b3c4d5-e6f7-8901-abcd-ef2345678906

			measure 'Sales PYTD' = CALCULATE([Total Sales], DATESYTD(SAMEPERIODLASTYEAR(DimDate[Date])))
				formatString: $#,##0.00
				displayFolder: 01_Sales Performance
				lineageTag: b2c3d4e5-f6a7-8901-bcde-f12345678907

			measure 'Sales YoY Growth %' = DIVIDE([Sales YTD] - [Sales PYTD], [Sales PYTD], BLANK())
				formatString: 0.0%;(0.0%);"-"
				displayFolder: 01_Sales Performance
				lineageTag: c2d3e4f5-a6b7-8901-cdef-023456789018

			measure 'Sales MoM Growth %' =
					VAR _CurrentMonth = [Total Sales]
					VAR _PreviousMonth = CALCULATE([Total Sales], DATEADD(DimDate[Date], -1, MONTH))
					RETURN DIVIDE(_CurrentMonth - _PreviousMonth, _PreviousMonth, BLANK())
				formatString: 0.0%;(0.0%);"-"
				displayFolder: 01_Sales Performance
				lineageTag: d2e3f4a5-b6c7-8901-def0-134567890129

			measure 'Avg Order Value' = DIVIDE([Total Sales], DISTINCTCOUNT(FactSales[OrderID]), BLANK())
				formatString: $#,##0.00
				displayFolder: 01_Sales Performance
				lineageTag: e2f3a4b5-c6d7-8901-ef01-24567890013a

			measure 'Total COGS' = SUMX(FactSales, FactSales[Quantity] * FactSales[UnitCost])
				formatString: $#,##0.00
				displayFolder: 02_Profitability
				lineageTag: f2a3b4c5-d6e7-8901-f012-3456789001ab

			measure 'Gross Profit' = [Total Sales] - [Total COGS]
				formatString: $#,##0.00
				displayFolder: 02_Profitability
				lineageTag: a3b4c5d6-e7f8-9012-abcd-ef34567890bc

			measure 'Gross Margin %' = DIVIDE([Gross Profit], [Total Sales], BLANK())
				formatString: 0.0%;(0.0%);"-"
				displayFolder: 02_Profitability
				lineageTag: b3c4d5e6-f7a8-9012-bcde-f034567890cd

			measure 'Total Stock Units' = SUM(FactInventory[Units])
				formatString: #,##0
				displayFolder: 03_Supply & Inventory
				lineageTag: c3d4e5f6-a7b8-9012-cdef-1034567890de

			measure 'Avg Daily Sales (30d)' =
					CALCULATE(
					    DIVIDE([Total Quantity Sold], 30),
					    DATESINPERIOD(DimDate[Date], LASTDATE(DimDate[Date]), -30, DAY)
					)
				formatString: #,##0.0
				displayFolder: 03_Supply & Inventory
				lineageTag: d3e4f5a6-b7c8-9012-def0-2034567890ef

			measure 'Days of Inventory Cover' = DIVIDE([Total Stock Units], [Avg Daily Sales (30d)], BLANK())
				formatString: #,##0.0 "days"
				displayFolder: 03_Supply & Inventory
				lineageTag: e3f4a5b6-c7d8-9012-ef01-3034567890f0

			measure 'Total Orders' = DISTINCTCOUNT(FactOrderFulfillment[OrderID])
				formatString: #,##0
				displayFolder: 04_Fulfillment & Logistics
				lineageTag: f3a4b5c6-d7e8-9012-f012-4034567890a1

			measure 'On-Time Deliveries' =
					CALCULATE(
					    [Total Orders],
					    FILTER(
					        FactOrderFulfillment,
					        FactOrderFulfillment[DeliveryDate] <= FactOrderFulfillment[ShipDate] + 7
					    )
					)
				formatString: #,##0
				displayFolder: 04_Fulfillment & Logistics
				lineageTag: a4b5c6d7-e8f9-0123-abcd-ef456789012b

			measure 'OTIF %' = DIVIDE([On-Time Deliveries], [Total Orders], BLANK())
				formatString: 0.0%;(0.0%);"-"
				displayFolder: 04_Fulfillment & Logistics
				lineageTag: b4c5d6e7-f8a9-0123-bcde-f0456789023c

			measure 'Avg Lead Time (Days)' =
					AVERAGEX(
					    FactOrderFulfillment,
					    DATEDIFF(
					        FactOrderFulfillment[OrderDate],
					        FactOrderFulfillment[DeliveryDate],
					        DAY
					    )
					)
				formatString: #,##0.0 "days"
				displayFolder: 04_Fulfillment & Logistics
				lineageTag: c4d5e6f7-a8b9-0123-cdef-10456789034d

			measure 'Avg Ship-to-Delivery (Days)' =
					AVERAGEX(
					    FactOrderFulfillment,
					    DATEDIFF(
					        FactOrderFulfillment[ShipDate],
					        FactOrderFulfillment[DeliveryDate],
					        DAY
					    )
					)
				formatString: #,##0.0 "days"
				displayFolder: 04_Fulfillment & Logistics
				lineageTag: d4e5f6a7-b8c9-0123-def0-20456789045e

			measure 'Total Campaign Spend' = SUM(FactCampaignSpend[Spend])
				formatString: $#,##0.00
				displayFolder: 05_Marketing & Campaigns
				lineageTag: e4f5a6b7-c8d9-0123-ef01-30456789056f

			measure 'Marketing ROI' = DIVIDE([Total Sales], [Total Campaign Spend], BLANK())
				formatString: #,##0.00"x"
				displayFolder: 05_Marketing & Campaigns
				lineageTag: f4a5b6c7-d8e9-0123-f012-40456789067a

			measure 'Revenue per Campaign \$' = DIVIDE([Total Sales], DISTINCTCOUNT(FactCampaignSpend[CampaignKey]), BLANK())
				formatString: $#,##0.00
				displayFolder: 05_Marketing & Campaigns
				lineageTag: a5b6c7d8-e9f0-1234-abcd-ef567890178b

			measure 'Total Customers' = DISTINCTCOUNT(FactSales[CustomerID])
				formatString: #,##0
				displayFolder: 06_Customer Analytics
				lineageTag: b5c6d7e8-f0a1-1234-bcde-f0567890289c

			measure 'Sales per Customer' = DIVIDE([Total Sales], [Total Customers], BLANK())
				formatString: $#,##0.00
				displayFolder: 06_Customer Analytics
				lineageTag: c5d6e7f8-a0b1-1234-cdef-106789039ad

			measure 'Repeat Customer Rate %' =
					VAR _RepeatCustomers =
					    COUNTROWS(
					        FILTER(
					            ADDCOLUMNS(
					                VALUES(FactSales[CustomerID]),
					                "OrderCount", CALCULATE(DISTINCTCOUNT(FactSales[OrderID]))
					            ),
					            [OrderCount] > 1
					        )
					    )
					RETURN
					    DIVIDE(_RepeatCustomers, [Total Customers], BLANK())
				formatString: 0.0%;(0.0%);"-"
				displayFolder: 06_Customer Analytics
				lineageTag: d5e6f7a8-b0c1-1234-def0-2067890ab0be

			measure 'Selected Period Sales' = CALCULATE([Total Sales], ALLSELECTED(DimDate))
				formatString: $#,##0.00
				displayFolder: 07_Dynamic & Context
				lineageTag: e5f6a7b8-c0d1-1234-ef01-3067890bc0cf

			measure 'Running Total Sales' =
					CALCULATE(
					    [Total Sales],
					    FILTER(
					        ALL(DimDate[Date]),
					        DimDate[Date] <= MAX(DimDate[Date])
					    )
					)
				formatString: $#,##0.00
				displayFolder: 07_Dynamic & Context
				lineageTag: f5a6b7c8-d0e1-1234-f012-4067890cd0d0

			measure 'Sales Rolling 3M' =
					CALCULATE(
					    [Total Sales],
					    DATESINPERIOD(DimDate[Date], LASTDATE(DimDate[Date]), -3, MONTH)
					)
				formatString: $#,##0.00
				displayFolder: 07_Dynamic & Context
				lineageTag: a6b7c8d9-e0f1-2345-abcd-ef678901e0e1

			measure System_Metadata_HTML =
					
					VAR LastRefreshDate = FORMAT(LASTDATE('DimDate'[Date]), "MMMM DD, YYYY hh:mm AM/PM")
					VAR ActiveCampaigns = CALCULATE(COUNTROWS('DimCampaign'))
					VAR TotalStock = FORMAT([Total Stock Units], "#,##0")
					
					RETURN
					"<div style='font-family: Segoe UI, sans-serif; padding: 15px; background-color: #F9FAFB; border-radius: 8px; border: 1px solid #E5E7EB; box-shadow: 2px 2px 4px rgba(0,0,0,0.05);'>
					    <h3 style='color: #1E3A8A; margin-top: 0; font-size: 16px; font-weight: 600;'>System & Data Status</h3>
					    <hr style='border: none; border-top: 1px solid #E5E7EB; margin-bottom: 10px;' />
					    <table style='width: 100%; font-size: 13px; color: #64748B; border-collapse: collapse;'>
					        <tr>
					            <td style='padding: 4px 0;'><strong>Last Data Refresh:</strong></td>
					            <td style='text-align: right;'>" & LastRefreshDate & "</td>
					        </tr>
					        <tr>
					            <td style='padding: 4px 0;'><strong>Active Marketing Campaigns:</strong></td>
					            <td style='text-align: right;'>" & ActiveCampaigns & "</td>
					        </tr>
					        <tr>
					            <td style='padding: 4px 0;'><strong>Monitored Stock Units:</strong></td>
					            <td style='text-align: right;'>" & TotalStock & "</td>
					        </tr>
					    </table>
					</div>"
				displayFolder: 00_HTML & UI/UX
				lineageTag: 46b23cd1-2143-4f3b-b047-089e6c96406a

			measure UI_4K_LandingPage_Refined = ```
					
					// 1. Dynamic User Context
					VAR CurrentUserEmail = USERPRINCIPALNAME()
					VAR DotPosition = SEARCH(".", CurrentUserEmail, 1, 0)
					VAR UserFirstName = IF(DotPosition > 0 && DotPosition < SEARCH("@", CurrentUserEmail, 1, 0), UPPER(LEFT(CurrentUserEmail, 1)) & MID(CurrentUserEmail, 2, DotPosition - 2), "Sohila")
					
					// 2. High-Level Model Aggregations
					VAR RefreshDate = FORMAT(MAX('DimDate'[Date]), "MMMM DD, YYYY")
					VAR MetricRevenue = FORMAT(SUM('FactSales'[LineTotal]), "$#,##0")
					VAR MetricOrders = FORMAT(COUNTROWS('FactSales'), "#,##0")
					VAR MetricCustomers = FORMAT(DISTINCTCOUNT('FactSales'[CustomerID]), "#,##0")
					VAR MetricStock = FORMAT(SUM('FactInventory'[Units]), "#,##0")
					VAR MetricCampaigns = FORMAT(COUNTROWS('DimCampaign'), "0")
					VAR MetricSpend = FORMAT(SUM('FactCampaignSpend'[Spend]), "$#,##0")
					
					RETURN
					"<!DOCTYPE html>
					<html style='height: 100%; width: 100%; margin: 0; padding: 0;'>
					<head>
					<meta charset='UTF-8'>
					<style>
					    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap');
					    
					    /* Hardware-Accelerated Animations */
					    @keyframes fadeInUp {
					        from { opacity: 0; transform: translate3d(0, 4vh, 0); }
					        to { opacity: 1; transform: translate3d(0, 0, 0); }
					    }
					    
					    @keyframes floatOrb {
					        0% { transform: translate3d(0, 0, 0) scale(1); }
					        50% { transform: translate3d(0, -4vh, 0) scale(1.05); }
					        100% { transform: translate3d(0, 0, 0) scale(1); }
					    }
					    
					    @keyframes pulseGlow {
					        0% { box-shadow: 0 0 0 0 rgba(99, 102, 241, 0.4); }
					        70% { box-shadow: 0 0 0 1.5vw rgba(99, 102, 241, 0); }
					        100% { box-shadow: 0 0 0 0 rgba(99, 102, 241, 0); }
					    }
					
					    body {
					        margin: 0;
					        padding: 0;
					        width: 100vw;
					        height: 100vh;
					        background-color: #0B0F19;
					        background-image: 
					            radial-gradient(circle at 15% 20%, rgba(30, 58, 138, 0.25) 0%, transparent 45%),
					            radial-gradient(circle at 85% 80%, rgba(124, 58, 237, 0.2) 0%, transparent 45%);
					        display: flex;
					        align-items: center;
					        justify-content: center;
					        font-family: 'Outfit', 'Segoe UI', sans-serif;
					        overflow: hidden;
					        box-sizing: border-box;
					    }
					
					    /* Ambient Orbs - Optimized with will-change */
					    .orb {
					        position: absolute;
					        border-radius: 50%;
					        filter: blur(8vw);
					        z-index: 1;
					        pointer-events: none;
					        will-change: transform;
					    }
					
					    .orb-1 {
					        width: 45vw; height: 45vw;
					        background: rgba(59, 130, 246, 0.12);
					        top: -10vw; left: 5vw;
					        animation: floatOrb 20s infinite ease-in-out;
					    }
					
					    .orb-2 {
					        width: 50vw; height: 50vw;
					        background: rgba(124, 58, 237, 0.1);
					        bottom: -15vw; right: 5vw;
					        animation: floatOrb 24s infinite ease-in-out -5s;
					    }
					
					    .wrapper {
					        display: flex;
					        flex-direction: column;
					        justify-content: space-between;
					        width: 90vw;
					        height: 88vh;
					        margin: auto;
					        z-index: 2;
					        box-sizing: border-box;
					    }
					
					    /* Header Bar */
					    .header-bar {
					        display: flex;
					        justify-content: space-between;
					        align-items: center;
					        border-bottom: 1px solid rgba(255, 255, 255, 0.08);
					        padding-bottom: 2vh;
					        animation: fadeInUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards;
					    }
					
					    .brand { display: flex; align-items: center; gap: 0.8vw; }
					    .brand-icon { font-size: 2vw; }
					    .brand-text { font-size: 1.6vw; font-weight: 700; letter-spacing: 0.1vw; color: #FFFFFF; }
					
					    .metadata-badges { display: flex; gap: 1vw; }
					    .badge {
					        background: rgba(255, 255, 255, 0.03);
					        border: 1px solid rgba(255, 255, 255, 0.08);
					        border-radius: 2vw;
					        padding: 0.6vh 1.2vw;
					        font-size: 0.9vw;
					        color: #94A3B8;
					        display: flex;
					        align-items: center;
					        gap: 0.5vw;
					        backdrop-filter: blur(4px);
					    }
					    .badge strong { color: #E2E8F0; font-weight: 600; }
					    .dot { width: 0.5vw; height: 0.5vw; border-radius: 50%; background: #10B981; box-shadow: 0 0 0.5vw #10B981; }
					
					    /* Hero Panel */
					    .hero-panel {
					        text-align: center;
					        margin-top: 3vh;
					        animation: fadeInUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) 0.1s forwards;
					        opacity: 0;
					    }
					    .hero-pre { font-size: 1vw; font-weight: 700; color: #38BDF8; letter-spacing: 0.2vw; text-transform: uppercase; margin-bottom: 1vh; }
					    .hero-title { font-size: 4vw; font-weight: 800; color: #FFFFFF; margin: 0; letter-spacing: -0.05vw; line-height: 1.1; }
					    .hero-title strong { 
					        background: linear-gradient(135deg, #60A5FA 0%, #A78BFA 100%);
					        -webkit-background-clip: text;
					        -webkit-text-fill-color: transparent;
					    }
					    .hero-desc { font-size: 1.2vw; color: #94A3B8; line-height: 1.6; margin: 1.5vh auto 0 auto; max-width: 55vw; }
					
					    /* Staggered Card Grid */
					    .card-grid {
					        display: grid;
					        grid-template-columns: repeat(4, 1fr);
					        gap: 1.5vw;
					        margin: 4vh 0;
					        width: 100%;
					    }
					
					    .card {
					        background: rgba(15, 23, 42, 0.5);
					        border-radius: 1vw;
					        border: 1px solid rgba(255, 255, 255, 0.05);
					        padding: 2vw;
					        display: flex;
					        flex-direction: column;
					        justify-content: space-between;
					        height: 32vh;
					        transition: all 0.4s cubic-bezier(0.16, 1, 0.3, 1);
					        cursor: pointer;
					        opacity: 0;
					        animation: fadeInUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards;
					        backdrop-filter: blur(12px);
					        will-change: transform;
					    }
					
					    /* Staggered Entrance */
					    .card:nth-child(1) { animation-delay: 0.2s; }
					    .card:nth-child(2) { animation-delay: 0.3s; }
					    .card:nth-child(3) { animation-delay: 0.4s; }
					    .card:nth-child(4) { animation-delay: 0.5s; }
					
					    .card:hover {
					        transform: translate3d(0, -1vh, 0);
					        background: rgba(30, 41, 59, 0.7);
					    }
					    .card:nth-child(1):hover { border-color: rgba(59, 130, 246, 0.5); box-shadow: 0 1vh 3vh rgba(59, 130, 246, 0.15); }
					    .card:nth-child(2):hover { border-color: rgba(16, 185, 129, 0.5); box-shadow: 0 1vh 3vh rgba(16, 185, 129, 0.15); }
					    .card:nth-child(3):hover { border-color: rgba(245, 158, 11, 0.5); box-shadow: 0 1vh 3vh rgba(245, 158, 11, 0.15); }
					    .card:nth-child(4):hover { border-color: rgba(236, 72, 153, 0.5); box-shadow: 0 1vh 3vh rgba(236, 72, 153, 0.15); }
					
					    .card-top { display: flex; justify-content: space-between; align-items: flex-start; }
					    .card-icon {
					        width: 3.5vw; height: 3.5vw;
					        border-radius: 0.8vw;
					        display: flex; align-items: center; justify-content: center;
					        font-size: 1.8vw;
					    }
					    .card:nth-child(1) .card-icon { background: rgba(59, 130, 246, 0.15); color: #60A5FA; }
					    .card:nth-child(2) .card-icon { background: rgba(16, 185, 129, 0.15); color: #34D399; }
					    .card:nth-child(3) .card-icon { background: rgba(245, 158, 11, 0.15); color: #FBBF24; }
					    .card:nth-child(4) .card-icon { background: rgba(236, 72, 153, 0.15); color: #F472B6; }
					
					    .card-arrow { font-size: 1.5vw; color: #475569; transition: transform 0.3s ease; }
					    .card:hover .card-arrow { transform: translateX(0.5vw); }
					    
					    .card-info { margin-top: auto; }
					    .card-title { font-size: 1.4vw; font-weight: 600; color: #FFFFFF; margin: 0 0 0.5vh 0; }
					    .card-desc { font-size: 0.95vw; color: #94A3B8; line-height: 1.5; margin: 0 0 2vh 0; }
					
					    /* Web-like Metric Pills */
					    .data-pills { display: flex; flex-wrap: wrap; gap: 0.5vw; }
					    .pill {
					        background: rgba(255, 255, 255, 0.05);
					        border: 1px solid rgba(255, 255, 255, 0.1);
					        padding: 0.4vh 0.8vw;
					        border-radius: 0.4vw;
					        font-size: 0.85vw;
					        color: #E2E8F0;
					        display: flex;
					        align-items: center;
					        gap: 0.4vw;
					    }
					    .pill-val { font-weight: 700; color: #FFFFFF; }
					
					    /* CTA Area */
					    .launch-area {
					        display: flex; justify-content: center; margin-top: 1vh;
					        animation: fadeInUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) 0.6s forwards;
					        opacity: 0;
					    }
					    .launch-btn {
					        background: linear-gradient(135deg, #4F46E5 0%, #7C3AED 100%);
					        color: #FFFFFF;
					        font-size: 1.2vw;
					        font-weight: 700;
					        padding: 1.2vw 4vw;
					        border-radius: 4vw;
					        cursor: pointer;
					        border: 1px solid rgba(255, 255, 255, 0.1);
					        animation: pulseGlow 3s infinite;
					        transition: all 0.3s cubic-bezier(0.16, 1, 0.3, 1);
					        letter-spacing: 0.1vw;
					        text-transform: uppercase;
					        box-shadow: 0 1vh 2vh rgba(79, 70, 229, 0.3);
					    }
					    .launch-btn:hover { transform: scale(1.03); box-shadow: 0 1.5vh 3vh rgba(124, 58, 237, 0.5); }
					
					</style>
					</head>
					<body>
					    <div class='orb orb-1'></div>
					    <div class='orb orb-2'></div>
					
					    <div class='wrapper'>
					        <div class='header-bar'>
					            <div class='brand'>
					                <span class='brand-text'>S&OP INTELLIGENCE</span>
					            </div>
					            <div class='metadata-badges'>
					                <div class='badge'><span class='dot'></span>Environment: <strong>Production</strong></div>
					                <div class='badge'>Sync: <strong>" & RefreshDate & "</strong></div>
					                <div class='badge'>Engine: <strong>DeepClean OS</strong></div>
					            </div>
					        </div>
					
					        <div class='hero-panel'>
					            <div class='hero-pre'>Control Center Active</div>
					            <h1 class='hero-title'>Welcome back, <strong>" & UserFirstName & "</strong></h1>
					            <p class='hero-desc'>Enterprise demand planning, customer channels, logistics status, and marketing ROI cubes have successfully updated. Select an operations portal below to begin analysis.</p>
					        </div>
					
					        <div class='card-grid'>
					            <!-- Card 1: Finance -->
					            <div class='card'>
					                <div class='card-top'>
					                    <div class='card-icon'>📈</div>
					                    <div class='card-arrow'>→</div>
					                </div>
					                <div class='card-info'>
					                    <h3 class='card-title'>Executive Summary</h3>
					                    <p class='card-desc'>Track aggregate revenues and dynamic targets.</p>
					                    <div class='data-pills'>
					                        <div class='pill'>Rev: <span class='pill-val'>" & MetricRevenue & "</span></div>
					                        <div class='pill'>Orders: <span class='pill-val'>" & MetricOrders & "</span></div>
					                    </div>
					                </div>
					            </div>
					
					            <!-- Card 2: Customers -->
					            <div class='card'>
					                <div class='card-top'>
					                    <div class='card-icon'>👥</div>
					                    <div class='card-arrow'>→</div>
					                </div>
					                <div class='card-info'>
					                    <h3 class='card-title'>Demand & Customers</h3>
					                    <p class='card-desc'>Deep dive into segmentations and geographic maps.</p>
					                    <div class='data-pills'>
					                        <div class='pill'>Active Accounts: <span class='pill-val'>" & MetricCustomers & "</span></div>
					                    </div>
					                </div>
					            </div>
					
					            <!-- Card 3: Logistics -->
					            <div class='card'>
					                <div class='card-top'>
					                    <div class='card-icon'>📦</div>
					                    <div class='card-arrow'>→</div>
					                </div>
					                <div class='card-info'>
					                    <h3 class='card-title'>Inventory & Logistics</h3>
					                    <p class='card-desc'>Monitor capacities, days of cover, and shipping.</p>
					                    <div class='data-pills'>
					                        <div class='pill'>Stock Units: <span class='pill-val'>" & MetricStock & "</span></div>
					                    </div>
					                </div>
					            </div>
					
					            <!-- Card 4: Marketing -->
					            <div class='card'>
					                <div class='card-top'>
					                    <div class='card-icon'>📢</div>
					                    <div class='card-arrow'>→</div>
					                </div>
					                <div class='card-info'>
					                    <h3 class='card-title'>Marketing & ROI</h3>
					                    <p class='card-desc'>Evaluate budgets, CTRs, and conversion indexes.</p>
					                    <div class='data-pills'>
					                        <div class='pill'>Campaigns: <span class='pill-val'>" & MetricCampaigns & "</span></div>
					                        <div class='pill'>Spend: <span class='pill-val'>" & MetricSpend & "</span></div>
					                    </div>
					                </div>
					            </div>
					        </div>
					
					        <div class='launch-area'>
					            <button class='launch-btn'>Launch Workspace</button>
					        </div>
					    </div>
					</body>
					</html>"
					```
				displayFolder: 00_HTML & UI/UX
				lineageTag: c24854a0-be84-4227-82e7-62895f2f823e

			column Value
				isHidden
				lineageTag: cabf892f-0e48-4e97-86a5-bbc4fc7ec7d1
				isNameInferred
				sourceColumn: [Value]

			partition KeyMeasures = calculated
				mode: import
				source = {(BLANK())}

			annotation PBI_ResultType = Table

			annotation PBI_NavigationStepName = Navigation

		relationship 79955cb1-6507-a07e-c220-b47283ff2ee2
			fromColumn: FactSales.FlagKey
			toColumn: DimOrderFlags.FlagKey

		relationship e650dafa-6ece-d86c-4663-5e14e894fb4b
			fromColumn: FactSales.CustomerID
			toColumn: DimCustomer.CustomerID

		relationship 36baa9cf-915b-f9be-685b-8333a199576e
			fromColumn: FactSales.ProductKey
			toColumn: DimProduct.ProductKey

		relationship 41458990-738f-b9de-56cf-367fd373f5de
			fromColumn: FactSales.BillToCityKey
			toColumn: DimGeo.GeoKey

		relationship 6b83ff2c-e36a-cb6b-420a-f33b8bc6233f
			isActive: false
			fromColumn: FactSales.ShipToCityKey
			toColumn: DimGeo.GeoKey

		relationship e942cf55-f6e6-7233-f03e-151cc99cdb02
			fromColumn: FactInventory.ProductKey
			toColumn: DimProduct.ProductKey

		relationship 8c471037-07c1-5c98-dac6-58e53b02a304
			fromColumn: FactCampaignSpend.CampaignKey
			toColumn: DimCampaign.CampaignKey

		relationship 1fe06857-8fe3-88ff-d34b-f4f22dae29af
			fromColumn: FactPromotionCoverage.CampaignKey
			toColumn: DimCampaign.CampaignKey

		relationship d3b8bdbb-ebde-9110-d56c-3bbb75da3851
			crossFilteringBehavior: bothDirections
			fromColumn: FactPromotionCoverage.ProductKey
			toColumn: DimProduct.ProductKey

		relationship 9b8ef54b-73e0-d75c-6aa4-c3637bf8aa06
			fromColumn: FactOrderFulfillment.CustomerID
			toColumn: DimCustomer.CustomerID

		relationship 50822ba5-c784-1796-88e0-ec87e1ce233d
			fromColumn: FactSales.OrderDate
			toColumn: DimDate.Date

		relationship bbd8aa6c-5e50-d34c-9622-0a8442847eba
			fromColumn: FactOrderFulfillment.OrderDate
			toColumn: DimDate.Date

		relationship dc0beaa9-2049-beee-3b81-ce379e4e1a36
			isActive: false
			fromColumn: FactOrderFulfillment.DeliveryDate
			toColumn: DimDate.Date

		relationship f5172d74-1e95-b7dd-0dd2-b60f558f5976
			isActive: false
			fromColumn: FactOrderFulfillment.InvoiceDate
			toColumn: DimDate.Date

		relationship 786c8cb1-cc92-f192-91e6-6af950d3d5de
			isActive: false
			fromColumn: FactOrderFulfillment.ShipDate
			toColumn: DimDate.Date

		relationship 2bd10ce1-c738-2324-93c6-0373b1f794b5
			isActive: false
			fromColumn: FactOrderFulfillment.PayDate
			toColumn: DimDate.Date

		relationship 948cfc52-0d77-3c10-6b2e-36674d6f0a97
			fromColumn: FactInventory.YearMonth
			toColumn: DimDate.Date

		relationship f0c93f68-3f6d-c5ce-69d8-234572cf47a5
			fromColumn: DimDate.Date
			toColumn: FactSalesTargets.Period

		relationship 16e8a4a3-230b-a35a-0117-85c02f1b8188
			isActive: false
			fromColumn: DimCustomer.City
			toColumn: DimGeo.City

		role 'Regional Sales Rep'
			modelPermission: read

			tablePermission DimCustomer = [Region] = LOOKUPVALUE(Security[Region], Security[UserEmail], USERPRINCIPALNAME())

			tablePermission DimGeo = [Region] = LOOKUPVALUE(Security[Region], Security[UserEmail], USERPRINCIPALNAME())

			annotation PBI_Id = 2818dbba4fcd47d494b7a96c223985cc

		role Executive
			modelPermission: read

			annotation PBI_Id = 9c0ef896914b4597abfb400ea5895df0

		role Admin
			modelPermission: readRefresh

			annotation PBI_Id = 4ce4c1b260cd4073b86260643f8de2c4

		cultureInfo en-US

		expression Address =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "Address", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"AddressID", Int64.Type}, {"Street", type text}, {"CityName", type text}}, "en-US")
				in
				  #"Changed column type"
			lineageTag: 47a04a2e-5944-4bbf-be47-7fcc13393a08
			queryGroup: 01_Staging

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression CUST_MASTER =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "CUST_MASTER", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"CustomerID", Int64.Type}, {"CustomerName", type text}, {"Segment", type text}, {"AddressID", Int64.Type}, {"AccountManager", type text}, {"PaymentTerms", type text}, {"hash_key", type text}, {"source_id", type text}}, "en-US")
				in
				  #"Changed column type"
			lineageTag: 125ddf3b-3972-4aa0-85b5-8ebf2b3f677c
			queryGroup: 01_Staging

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression cities =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "cities", Kind = "Sheet"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Column1", type text}, {"Column2", type text}}, "en-US"),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed column type", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CityName", type text}, {"RegionName", type text}})
				in
				  #"Changed Type"
			lineageTag: ee404aa9-83da-4f6c-99a0-665d0173c0ea
			queryGroup: 01_Staging

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression customer_contacts =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "customer_contacts", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"CustomerID", Int64.Type}, {"ContactName", type text}, {"Email", type text}, {"IsPrimary", type logical}}, "en-US"),
				    #"Filtered Rows" = Table.SelectRows(#"Changed column type", each ([IsPrimary] = true))
				in
				  #"Filtered Rows"
			lineageTag: 74724387-c650-4b12-885c-167b26fdf186
			queryGroup: 01_Staging

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression regions =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "regions", Kind = "Sheet"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Column1", type text}}, "en-US"),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed column type", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"RegionName", type text}})
				in
				  #"Changed Type"
			lineageTag: 72f618a4-9f88-4c95-9cb5-2065198340d7
			queryGroup: 01_Staging

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression user_details =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "user_details", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"UserID", Int64.Type}, {"CreditLimit", Int64.Type}, {"Phone", type text}}, "en-US")
				in
				  #"Changed column type"
			lineageTag: 0d16637a-d25e-45a6-b5e9-531fefe787bf
			queryGroup: 01_Staging

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression products =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "products", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"ProductCode", type text}, {"ProductName", type text}, {"Brand", type text}, {"SubcategoryName", type text}, {"UnitPrice", type number}, {"PrimarySupplier", type text}, {"ProductDescription", type text}, {"hash_key", type text}, {"source_id", type text}}, "en-US")
				in
				  #"Changed column type"
			lineageTag: 19ec4594-1475-4ee9-a5b7-180b6e77b2e0
			queryGroup: 01_Staging

			annotation PBI_ResultType = Table

		expression subcategories =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "subcategories", Kind = "Sheet"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Column1", type text}}, "en-US"),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed column type", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CategorySubcategory", type text}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "CategorySubcategory", Splitter.SplitTextByDelimiter("|", QuoteStyle.Csv), {"Category", "Subcategory"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Category", type text}, {"Subcategory", type text}}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Changed Type1",{{"Category", Text.Proper, type text}, {"Subcategory", Text.Proper, type text}})
				in
				    #"Capitalized Each Word"
			lineageTag: 6e699469-0055-4c42-bc0d-b045c86a610c
			queryGroup: 01_Staging

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression orders =
				let
				    Source = Table.Combine({ORDERS_2025, ORDERS_2026}),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"LegacyRef", "SourceFile", "GiftMessage", "OrderNotes"})
				in
				    #"Removed Columns"
			lineageTag: 7f1cf99d-e9ab-4809-bd74-d2d9192651a8
			queryGroup: 01_Staging

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression channels =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjRQ0lHyz8vJzEtVCC7JL0pVitWJVjICiQalliRm5igEJBaV5KUWgcWNQeLhGfk5qcWJORClJiAht8zUnBSFYLBYLAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ChannelCode = _t, ChannelName = _t]),
				  #"Changed column type" = Table.TransformColumnTypes(Source, {{"ChannelCode", Int64.Type}, {"ChannelName", type text}}, "en-US")
				in
				  #"Changed column type"
			lineageTag: 7ae3efe5-d6f6-49aa-b518-f834eec5caef
			queryGroup: 01_Staging

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression ORDERS_2025 =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "ORDERS_2025", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"OrderID", type text}, {"LegacyRef", type text}, {"CustomerName", type text}, {"CustomerCity", type text}, {"RegionName", type text}, {"ShipToCity", type text}, {"BillToCity", type text}, {"OrderDate", type datetime}, {"OrderChannel", Int64.Type}, {"Status", type text}, {"Priority", type text}, {"OrderTotal", type number}, {"OrderNotes", type text}, {"SourceFile", type text}}, "en-US")
				in
				  #"Changed column type"
			lineageTag: 52bd3776-8ab5-4da3-826f-3a90818dda7d
			queryGroup: 01_Staging

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression ORDERS_2026 =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "ORDERS_2026", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"OrderID", type text}, {"CustomerName", type text}, {"CustomerCity", type text}, {"RegionName", type text}, {"ShipToCity", type text}, {"BillToCity", type text}, {"OrderDate", type datetime}, {"OrderChannel", Int64.Type}, {"Status", type text}, {"Priority", type text}, {"OrderTotal", type number}, {"OrderNotes", type text}}, "en-US")
				in
				  #"Changed column type"
			lineageTag: 64f89755-d37b-44ae-9796-89c093ecd183
			queryGroup: 01_Staging

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression order_line_items =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "order_line_items", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"LineID", type text}, {"OrderID", type text}, {"ProductName", type text}, {"Quantity", Int64.Type}, {"UnitPrice", type number}, {"UnitCost", type number}, {"DiscountPct", type number}, {"LineTotal", type number}}, "en-US")
				in
				  #"Changed column type"
			lineageTag: 9727c124-da7d-4017-8133-1bba6354ae40
			queryGroup: 01_Staging

			annotation PBI_ResultType = Table

		expression CAMPAIGN_LOG =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "CAMPAIGN_LOG", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"CampaignName", type text}, {"Channel", type text}, {"StartDate", type date}, {"EndDate", type date}, {"Budget", Int64.Type}, {"Date", type date}, {"Impressions", Int64.Type}, {"Clicks", Int64.Type}, {"Spend", type number}}, "en-US")
				in
				  #"Changed column type"
			lineageTag: 5fbda42a-986d-4db8-bf28-466677215060
			queryGroup: 01_Staging

			annotation PBI_ResultType = Table

		expression INVOICES =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "INVOICES", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"InvoiceID", type text}, {"OrderID", type text}, {"CustomerName", type text}, {"InvoiceDate", type date}, {"Amount", type number}}, "en-US")
				in
				  #"Changed column type"
			lineageTag: 6bda6a9d-9f45-430b-92a9-95114d6524ae
			queryGroup: 01_Staging

			annotation PBI_ResultType = Table

		expression campaign_skus =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "campaign_skus", Kind = "Sheet"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Column1", type text}, {"Column2", type text}}, "en-US"),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed column type", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CampaignName", type text}, {"PromotedSKUs", type text}})
				in
				  #"Changed Type"
			lineageTag: b4cf26c8-cac1-4d9a-bf50-a06bd29c3ef6
			queryGroup: 01_Staging

			annotation PBI_ResultType = Table

			annotation PBI_NavigationStepName = Navigation

		expression exchange_rates =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "exchange_rates", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Currency", type text}, {"Rate", type number}, {"Date", type date}}, "en-US")
				in
				  #"Changed column type"
			lineageTag: ad067bbc-bfb1-4c1c-9701-251af64499cb
			queryGroup: 01_Staging

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression inventory =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "inventory", Kind = "Sheet"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Column1", type text}}, "en-US")
				in
				  #"Changed column type"
			lineageTag: fc374313-1faa-447d-9813-851ef1998234
			queryGroup: 01_Staging

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression invoice_lines =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "invoice_lines", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"InvoiceLineID", type text}, {"InvoiceID", type text}, {"ProductName", type text}, {"Amount", type number}}, "en-US")
				in
				  #"Changed column type"
			lineageTag: f3be3005-b328-46a4-8e5d-6d5f38053573
			queryGroup: 01_Staging

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression payments =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "payments", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"PaymentID", type text}, {"InvoiceID", type text}, {"CustomerName", type text}, {"PayDate", type date}, {"Amount", type number}}, "en-US")
				in
				  #"Changed column type"
			lineageTag: f051197f-be21-4d56-bf2b-7d384d42505d
			queryGroup: 01_Staging

			annotation PBI_ResultType = Table

		expression sales_targets =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "sales_targets", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Period", type date}, {"TargetRevenue", Int64.Type}}, "en-US")
				in
				  #"Changed column type"
			lineageTag: b5ac156e-ef37-4e40-8484-429b959cf6c2
			queryGroup: 01_Staging

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression shipments =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "shipments", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"ShipmentID", type text}, {"OrderID", type text}, {"ShipMode", type text}, {"ShipDate", type date}, {"DeliveryDate", type date}}, "en-US")
				in
				  #"Changed column type"
			lineageTag: 8da78d97-7b38-4fd8-a010-7fdf9ecfa9b4
			queryGroup: 01_Staging

			annotation PBI_ResultType = Table

		expression ExcelSource =
				let
				  Source = Excel.Workbook(File.Contents("D:\courses\Data Science\powerbi-ultimate-course\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				  Buffered = Table.Buffer(Source)
				in
				  Buffered
			lineageTag: e8d7a6f2-a5b6-7890-bcde-f01234567890
			queryGroup: 01_Staging

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		queryGroup 01_Staging

			annotation PBI_QueryGroupOrder = 0

		queryGroup 02_Dimensions

			annotation PBI_QueryGroupOrder = 1

		queryGroup 03_Facts

			annotation PBI_QueryGroupOrder = 2

		queryGroup 04_Support

			annotation PBI_QueryGroupOrder = 3

		annotation __PBI_TimeIntelligenceEnabled = 0

		annotation PBI_QueryOrder = ["ExcelSource","Address","CAMPAIGN_LOG","CUST_MASTER","INVOICES","ORDERS_2025","ORDERS_2026","campaign_skus","cities","customer_contacts","exchange_rates","inventory","invoice_lines","order_line_items","payments","products","regions","sales_targets","Security","shipments","subcategories","user_details","DimCustomer","DimProduct","DimOrderFlags","DimGeo","DimCampaign","DimDate","orders","channels","FactSales","FactInventory","FactCampaignSpend","FactPromotionCoverage","FactOrderFulfillment","FactSalesTargets"]

		annotation PBI_ProTooling = ["DevMode","TMDLView_Desktop","MCP-PBIModeling"]

